export const gta5Areas = [
    "Los Santos International Airport",
    "Alamo Sea",
    "Alta",
    "Fort Zancudo",
    "Banning",
    "Baytree Canyon",
    "Vespucci Beach",
    "Banham Canyon",
    "Braddock Pass",
    "Braddock Tunnel",
    "Burton",
    "Calafia Bridge",
    "Raton Canyon",
    "Cassidy Creek",
    "Chamberlain Hills",
    "Vinewood Hills",
    "Chumash",
    "Chiliad Mountain State Wilderness",
    "Countryside",
    "Cypress Flats",
    "Davis",
    "Del Perro Beach",
    "Del Perro",
    "La Puerta",
    "Grand Senora Desert",
    "Downtown",
    "Downtown Vinewood",
    "East Vinewood",
    "El Burro Heights",
    "Eclipse",
    "El Gordo Lighthouse",
    "East Los Santos",
    "Elysian Island",
    "Galilee",
    "Galileo Park",
    "GWC and Golfing Society",
    "Grapeseed",
    "Great Chaparral",
    "Harmony",
    "Hawick",
    "Heart Attacks Beach",
    "Vinewood Racetrack",
    "Humane Labs and Research",
    "Bolingbroke Penitentiary",
    "Little Seoul",
    "Land Act Reservoir",
    "Lago Zancudo",
    "Land Act Dam",
    "La Mesa",
    "La Puerta",
    "Los Santos Freeway",
    "Mirror Park",
    "Morningwood",
    "Richards Majestic",
    "Mount Chiliad",
    "Mount Gordo",
    "Mount Josiah",
    "Murrieta Heights",
    "North Chumash",
    "Galileo Observatory",
    "Pacific Ocean",
    "Paleto Cove",
    "Paleto Bay",
    "Paleto Forest",
    "Palomino Highlands",
    "Palmer-Taylor Power Station",
    "Pacific Bluffs",
    "Pillbox Hill",
    "Procopio Beach",
    "North Yankton",
    "Rancho",
    "Richman Glen",
    "Richman",
    "Rockford Hills",
    "Redwood Lights Track",
    "San Andreas",
    "San Chianski Mountain Range",
    "Sandy Shores",
    "Mission Row",
    "Stab City",
    "South Los Santos",
    "Maze Bank Arena",
    "Strawberry",
    "Tataviam Mountains",
    "Terminal",
    "Textile City",
    "Tongva Hills",
    "Tongva Valley",
    "Utopia Gardens",
    "Vespucci Canals",
    "Vespucci",
    "Vinewood",
    "Ron Alternates Wind Farm",
    "West Mirror Drive",
    "West Vinewood",
    "Zancudo River",
    "Senora Freeway",
];
