[install]
minimumReleaseAge = 86400 # 1 day
minimumReleaseAgeExcludes = [
  "@types/node",
  "typescript",
  "react",
  "react-dom",
  "@tanstack/react-start",
  "@tanstack/react-router",
  "@tanstack/router-core",
  "@tanstack/history",
  "@tanstack/start-storage-context",
  "@tanstack/router-plugin",
  "@tanstack/router-generator",
  "@tanstack/react-start-rsc",
  "@tanstack/start-client-core",
  "@tanstack/start-plugin-core",
  "@tanstack/start-server-core",
  "@tanstack/react-start-client",
  "@tanstack/react-start-server",
]
