/**
 * This file is automatically generated.
 * DO NOT EDIT manually
 */

export const controllers = {
  Auth: () => import('#controllers/auth_controller'),
  Characters: () => import('#controllers/characters_controller'),
  Contact: () => import('#controllers/contact_controller'),
  DashboardArticles: () => import('#controllers/dashboard_articles_controller'),
  DashboardEvents: () => import('#controllers/dashboard_events_controller'),
  DashboardJobs: () => import('#controllers/dashboard_jobs_controller'),
  DashboardPages: () => import('#controllers/dashboard_pages_controller'),
  Departments: () => import('#controllers/departments_controller'),
  Donate: () => import('#controllers/donate_controller'),
  Events: () => import('#controllers/events_controller'),
  Home: () => import('#controllers/home_controller'),
  JobApplications: () => import('#controllers/job_applications_controller'),
  Jobs: () => import('#controllers/jobs_controller'),
  News: () => import('#controllers/news_controller'),
  Parishes: () => import('#controllers/parishes_controller'),
  Payments: () => import('#controllers/payments_controller'),
  Profile: () => import('#controllers/profile_controller'),
  RegisterParishioners: () => import('#controllers/register_parishioners_controller'),
  Services: () => import('#controllers/services_controller'),
}
