/**
 * This file is automatically generated.
 * DO NOT EDIT manually
 */

export const controllers = {
  auth: {
    Auth: () => import('#app/auth/controllers/auth_controller'),
  },
  billing: {
    Payments: () => import('#app/billing/controllers/payments_controller'),
  },
  careers: {
    DashboardJobPostings: () => import('#app/careers/controllers/dashboard_job_postings_controller'),
    JobApplications: () => import('#app/careers/controllers/job_applications_controller'),
    JobPostings: () => import('#app/careers/controllers/job_postings_controller'),
  },
  characters: {
    Characters: () => import('#app/characters/controllers/characters_controller'),
  },
  dashboard: {
    Dashboard: () => import('#app/dashboard/controllers/dashboard_controller'),
  },
  donate: {
    Donate: () => import('#app/donate/controllers/donate_controller'),
  },
  pages: {
    Contact: () => import('#app/pages/controllers/contact_controller'),
    Decrees: () => import('#app/pages/controllers/decrees_controller'),
    Departments: () => import('#app/pages/controllers/departments_controller'),
    Home: () => import('#app/pages/controllers/home_controller'),
    Parishes: () => import('#app/pages/controllers/parishes_controller'),
    RegisterParishioners: () => import('#app/pages/controllers/register_parishioners_controller'),
    Services: () => import('#app/pages/controllers/services_controller'),
  },
  posts: {
    DashboardPosts: () => import('#app/posts/controllers/dashboard_posts_controller'),
    Posts: () => import('#app/posts/controllers/posts_controller'),
  },
  scheduledEvents: {
    DashboardScheduledEvents: () => import('#app/scheduled_events/controllers/dashboard_scheduled_events_controller'),
    ScheduledEvents: () => import('#app/scheduled_events/controllers/scheduled_events_controller'),
  },
  users: {
    Account: () => import('#app/users/controllers/account_controller'),
    DashboardUsers: () => import('#app/users/controllers/dashboard_users_controller'),
  },
}
