export const DISCORD_LIMITS = {
  MAX_EMBEDS: 10,
  MAX_CONTENT_LENGTH: 2000,
  MAX_EMBED_TITLE_LENGTH: 256,
  MAX_EMBED_DESCRIPTION_LENGTH: 4096,
  MAX_EMBED_FIELDS: 25,
  MAX_EMBED_FIELD_NAME_LENGTH: 256,
  MAX_EMBED_FIELD_VALUE_LENGTH: 1024,
  REQUEST_TIMEOUT: 10_000,
  DEFAULT_RETRIES: 3,
} as const
