/**
 * This file is automatically generated
 * DO NOT EDIT manually
 * Run "node ace migration:run" command to re-generate this file
 */

import { BaseModel, column } from '@adonisjs/lucid/orm'
import { DateTime } from 'luxon'

export class AccountSchema extends BaseModel {
  static $columns = ['id', 'userId', 'accountId', 'providerId', 'accessToken', 'refreshToken', 'accessTokenExpiresAt', 'refreshTokenExpiresAt', 'scope', 'createdAt', 'updatedAt'] as const
  $columns = AccountSchema.$columns
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare userId: number | null
  @column()
  declare accountId: string
  @column()
  declare providerId: string
  @column()
  declare accessToken: string | null
  @column()
  declare refreshToken: string | null
  @column.dateTime()
  declare accessTokenExpiresAt: DateTime | null
  @column.dateTime()
  declare refreshTokenExpiresAt: DateTime | null
  @column()
  declare scope: string | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class JobPostingSchema extends BaseModel {
  static $columns = ['id', 'slug', 'title', 'summary', 'reportsTo', 'department', 'responsibilities', 'requirements', 'salary', 'employmentType', 'isActive', 'postedAt', 'expiresAt', 'createdAt', 'updatedAt', 'skills'] as const
  $columns = JobPostingSchema.$columns
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare slug: string
  @column()
  declare title: string
  @column()
  declare summary: string | null
  @column()
  declare reportsTo: string | null
  @column()
  declare department: string
  @column()
  declare responsibilities: any | null
  @column()
  declare requirements: any | null
  @column()
  declare salary: number | null
  @column()
  declare employmentType: string
  @column()
  declare isActive: boolean
  @column.dateTime()
  declare postedAt: DateTime | null
  @column.dateTime()
  declare expiresAt: DateTime | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare skills: any | null
}

export class NewsSchema extends BaseModel {
  static $columns = ['id', 'title', 'slug', 'category', 'content', 'excerpt', 'coverImageUrl', 'status', 'publishedAt', 'authorId', 'createdAt', 'updatedAt'] as const
  $columns = NewsSchema.$columns
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare title: string
  @column()
  declare slug: string
  @column()
  declare category: string | null
  @column()
  declare content: string
  @column()
  declare excerpt: string | null
  @column()
  declare coverImageUrl: string | null
  @column()
  declare status: string
  @column.dateTime()
  declare publishedAt: DateTime | null
  @column()
  declare authorId: bigint | number | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class PermissionSchema extends BaseModel {
  static $columns = ['id', 'slug', 'name', 'description', 'createdAt', 'updatedAt'] as const
  $columns = PermissionSchema.$columns
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare slug: string
  @column()
  declare name: string
  @column()
  declare description: string | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class RolePermissionSchema extends BaseModel {
  static $columns = ['roleId', 'permissionId'] as const
  $columns = RolePermissionSchema.$columns
  @column()
  declare roleId: number
  @column()
  declare permissionId: number
}

export class RoleSchema extends BaseModel {
  static $columns = ['id', 'slug', 'name', 'description', 'createdAt', 'updatedAt', 'hierarchyOrder'] as const
  $columns = RoleSchema.$columns
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare slug: string
  @column()
  declare name: string
  @column()
  declare description: string | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare hierarchyOrder: number
}

export class ScheduledEventSchema extends BaseModel {
  static $columns = ['id', 'title', 'slug', 'description', 'content', 'location', 'parishId', 'coverImageUrl', 'flyerUrl', 'registrationRequired', 'maxParticipants', 'startDate', 'endDate', 'createdAt', 'updatedAt'] as const
  $columns = ScheduledEventSchema.$columns
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare title: string
  @column()
  declare slug: string
  @column()
  declare description: string
  @column()
  declare content: string
  @column()
  declare location: string
  @column()
  declare parishId: number | null
  @column()
  declare coverImageUrl: string | null
  @column()
  declare flyerUrl: string | null
  @column()
  declare registrationRequired: boolean | null
  @column()
  declare maxParticipants: number | null
  @column.dateTime()
  declare startDate: DateTime
  @column.dateTime()
  declare endDate: DateTime | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class UserRoleSchema extends BaseModel {
  static $columns = ['userId', 'roleId'] as const
  $columns = UserRoleSchema.$columns
  @column()
  declare userId: number
  @column()
  declare roleId: number
}

export class UserSchema extends BaseModel {
  static $columns = ['id', 'name', 'createdAt', 'updatedAt'] as const
  $columns = UserSchema.$columns
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare name: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}
