import type { GiftCategory, GiftProduct } from '#/features/gift-shop/types/gift-shop.types.ts'

export const GIFT_ORDER_SOURCE = 'gift_shop'

export const GIFT_ORDER_QUANTITY_MAX = 10

export const GIFT_SHOP_CATEGORIES: readonly GiftCategory[] = [
  { id: 'jewelry', label: 'Bijoux' },
  { id: 'rosaries', label: 'Chapelets' },
  { id: 'books', label: 'Livres et autres' },
  { id: 'crosses-and-crucifixes', label: 'Croix et Crucifix' },
  { id: 'made-by-catholics', label: 'Made by Catholique' },
  { id: 'souvenirs', label: 'Souvenirs / Cadeaux' },
  { id: 'children', label: 'Pour les enfants' },
  { id: 'special-occasions', label: 'Occasions spéciales' },
  { id: 'irish', label: 'Irlandais' },
  { id: 'other', label: 'Autres' },
]

export const GIFT_SHOP_PRODUCTS: readonly GiftProduct[] = [
  {
    id: 'carte-identite-catholique',
    categoryIds: ['made-by-catholics', 'other'],
    itemId: 1770,
    name: "Carte d'Identité Catholique",
    description: 'A porter sur soi en permanence.',
    price: 200,
    imageSrc: 'https://i.imgur.com/1kPbL5i.png',
  },
  {
    id: 'crucifix-mural-noyer',
    categoryIds: ['crosses-and-crucifixes'],
    itemId: 2093,
    name: 'Crucifix Mural Italien en Bois de Noyer',
    description: 'Grand crucifix mural en bois de noyer, finition italienne. Taille: 60cm',
    price: 1_920,
    imageSrc: 'https://i.imgur.com/LtoKuEm.png',
  },
  {
    id: 'croix-benediction-irlandaise',
    categoryIds: ['irish', 'special-occasions', 'crosses-and-crucifixes'],
    itemId: 2094,
    name: 'Croix Murale Bénédiction Irlandaise',
    description: 'Croix murale celtique. Taille : 20cm',
    price: 289,
    imageSrc: 'https://i.imgur.com/cM2LW9N.png',
  },
  {
    id: 'statuette-saint-francois',
    categoryIds: ['made-by-catholics'],
    itemId: 2633,
    name: "Statuette Saint François d'Assise",
    description: 'Statuette du saint patron des animaux et de la nature.',
    price: 449,
    imageSrc: 'https://i.imgur.com/ydEwFLA.png',
  },
  {
    id: 'statuette-saint-patrick',
    categoryIds: ['made-by-catholics', 'irish'],
    itemId: 2634,
    name: 'Statuette Saint Patrick',
    description: "Statuette de l'évangélisateur et saint patron de l'Irlande, saint Patrick.",
    price: 229,
    imageSrc: 'https://i.imgur.com/0MKdUF7.png',
  },
  {
    id: 'statuette-crucifixion',
    categoryIds: ['made-by-catholics'],
    itemId: 2635,
    name: 'Statuette de la Crucifixion',
    description: '',
    price: 229,
    imageSrc: 'https://i.imgur.com/sciPDVX.png',
  },
  {
    id: 'statuette-coeur-immacule',
    categoryIds: ['made-by-catholics'],
    itemId: 2636,
    name: 'Statuette du Cœur Immaculé de Marie',
    description: 'Matériaux : Mélange de résine et de pierre',
    price: 625,
    imageSrc: 'https://i.imgur.com/UBzhOcs.png',
  },
  {
    id: 'bible-st-joseph',
    categoryIds: ['books'],
    itemId: 2637,
    name: 'New Catholic Bible Édition St Joseph',
    description: 'Bible, édition Saint Joseph.',
    price: 595,
    imageSrc: 'https://i.imgur.com/guGCrtj.png',
  },
  {
    id: 'biblia-america',
    categoryIds: ['books'],
    itemId: 2638,
    name: 'Biblia de América',
    description: 'La Bible en espagnol, édition América.',
    price: 495,
    imageSrc: 'https://i.imgur.com/NQgcNqm.png',
  },
  {
    id: 'collier-guadalupe',
    categoryIds: ['jewelry'],
    itemId: 3546,
    name: 'Collier à Pendentif Notre-Dame de Guadalupe',
    description: 'Collier en or orné d’un pendentif de Notre-Dame de Guadalupe.',
    price: 6_800,
    imageSrc: 'https://i.imgur.com/J5NLhiB.png',
  },
  {
    id: 'chapelet-lourdes',
    categoryIds: ['rosaries'],
    itemId: 3547,
    name: 'Chapelet Notre-Dame de Lourdes',
    description: 'Matériaux : Verre',
    price: 5_095,
    imageSrc: 'https://i.imgur.com/8e9vVTl.png',
  },
  {
    id: 'arche-noe-blocs',
    categoryIds: ['children', 'souvenirs'],
    itemId: 3548,
    name: 'Arche de Noé - Jeu de blocs en bois',
    description: 'Matériaux : Bois',
    price: 280,
    imageSrc: 'https://i.imgur.com/vFL6LBQ.png',
  },
  {
    id: 'crucifix-mural-antique-or',
    categoryIds: ['crosses-and-crucifixes'],
    itemId: 6243,
    name: 'Crucifix mural Antique en or',
    description: 'Crucifix mural en or. Taille : 21,59cm',
    price: 2_495,
    imageSrc: 'https://i.imgur.com/5viXgco.png',
  },
  {
    id: 'collier-croix-argent',
    categoryIds: ['jewelry'],
    itemId: 6300,
    name: 'Collier Croix Crucifix Classique (Argent sterling)',
    description: 'Collier en argent sterling orné d’une croix classique. Fabriqué en Italie',
    price: 1_640,
    imageSrc: 'https://i.imgur.com/tiJMojZ.png',
  },
  {
    id: 'medaille-saint-patrick',
    categoryIds: ['jewelry', 'souvenirs', 'irish', 'special-occasions'],
    itemId: 6301,
    name: 'Médaille Saint Patrick',
    description: 'Médaille de saint Patrick, patron de l’Irlande.',
    price: 495,
    imageSrc: 'https://i.imgur.com/GCR2EZA.png',
  },
  {
    id: 'plaque-priere-irlandaise',
    categoryIds: ['souvenirs', 'irish', 'special-occasions'],
    itemId: 6302,
    name: 'Plaque Irlandaise',
    description: 'Plaque en résine gravée d’une prière irlandaise.',
    price: 280,
    imageSrc: 'https://i.imgur.com/sZoey21.png',
  },
  {
    id: 'medaille-pompiers',
    categoryIds: ['jewelry', 'souvenirs', 'special-occasions'],
    itemId: 6303,
    name: 'Médaille des Pompiers',
    description: 'Médaille en argent sterling pour la protection des pompiers',
    price: 770,
    imageSrc: 'https://i.imgur.com/CvgDsM1.png',
  },
  {
    id: 'bouteille-eau-enseignants',
    categoryIds: ['souvenirs', 'special-occasions'],
    itemId: 6304,
    name: "Bouteille d'Eau Pour Les Enseignants",
    description: 'Matériaux : Verre',
    price: 190,
    imageSrc: 'https://i.imgur.com/7voBZSr.png',
  },
  {
    id: 'creche-noel-italienne',
    categoryIds: ['special-occasions'],
    itemId: 6305,
    name: 'Crèche de Noël Italienne',
    description: 'Matériaux : Bois / Polymère',
    price: 1_380,
    imageSrc: 'https://i.imgur.com/6AEXdGd.png',
  },
  {
    id: 'bougeoir-mariage',
    categoryIds: ['special-occasions'],
    itemId: 6306,
    name: 'Bougeoir de mariage',
    description: 'Matériaux : Résine',
    price: 495,
    imageSrc: 'https://i.imgur.com/Zd20kJn.png',
  },
  {
    id: 'chapelet-saint-michel',
    categoryIds: ['rosaries'],
    itemId: 6307,
    name: 'Chapelet Policier St. Michel',
    description: 'Matériaux : Bois',
    price: 4_095,
    imageSrc: 'https://i.imgur.com/bH7EIgT.png',
  },
  {
    id: 'chapelet-jujubier-onyx',
    categoryIds: ['rosaries'],
    itemId: 6308,
    name: 'Chapelet - Bois de Jujubier et Onyx Véritable Multicolore',
    description: 'Matériaux : Bois de jujubier',
    price: 3_800,
    imageSrc: 'https://i.imgur.com/34H5qPG.png',
  },
  {
    id: 'crucifix-mural-sainte-trinite',
    categoryIds: ['crosses-and-crucifixes'],
    itemId: 6309,
    name: 'Crucifix Mural - Sainte Trinité',
    description: 'Matériaux: Mélange de résine et de pierre. Taille : 26cm',
    price: 4_000,
    imageSrc: 'https://i.imgur.com/ncC7lq2.png',
  },
]

export const GIFT_SHOP_PRODUCT_BY_ID: ReadonlyMap<string, GiftProduct> = new Map(
  GIFT_SHOP_PRODUCTS.map((product) => [product.id, product])
)
