/**
 * This file is automatically generated.
 * DO NOT EDIT manually
 */

/// <reference path="./manifest.d.ts" />
import type { InferData, InferVariants } from '@adonisjs/core/types/transformers'
import type { InferSharedProps } from '@adonisjs/inertia/types'
import type EventTransformer from '#transformers/event_transformer'
import type JobTransformer from '#transformers/job_transformer'
import type NewsTransformer from '#transformers/news_transformer'
import type UserTransformer from '#transformers/user_transformer'
import type InertiaMiddleware from '#middleware/inertia_middleware'

export namespace Data {
  export type Event = InferData<EventTransformer>
  export namespace Event {
    export type Variants = InferVariants<EventTransformer>
  }
  export type Job = InferData<JobTransformer>
  export namespace Job {
    export type Variants = InferVariants<JobTransformer>
  }
  export type News = InferData<NewsTransformer>
  export namespace News {
    export type Variants = InferVariants<NewsTransformer>
  }
  export type User = InferData<UserTransformer>
  export namespace User {
    export type Variants = InferVariants<UserTransformer>
  }
  export type SharedProps = InferSharedProps<InertiaMiddleware>
}
