/**
 * This file is automatically generated.
 * DO NOT EDIT manually
 */

/// <reference path="./manifest.d.ts" />
import type { InferData, InferVariants } from '@adonisjs/core/types/transformers'
import type { InferSharedProps } from '@adonisjs/inertia/types'
import type CareersJobPostingTransformer from '#app/careers/transformers/job_posting_transformer'
import type PostsPostTransformer from '#app/posts/transformers/post_transformer'
import type RolesRoleTransformer from '#app/roles/transformers/role_transformer'
import type ScheduledEventsScheduledEventTransformer from '#app/scheduled_events/transformers/scheduled_event_transformer'
import type UsersUserTransformer from '#app/users/transformers/user_transformer'
import type InertiaMiddleware from '#core/middleware/inertia_middleware'

export namespace Data {
  export namespace Careers {
    export type JobPosting = InferData<CareersJobPostingTransformer>
    export namespace JobPosting {
      export type Variants = InferVariants<CareersJobPostingTransformer>
    }
  }
  export namespace Posts {
    export type Post = InferData<PostsPostTransformer>
    export namespace Post {
      export type Variants = InferVariants<PostsPostTransformer>
    }
  }
  export namespace Roles {
    export type Role = InferData<RolesRoleTransformer>
    export namespace Role {
      export type Variants = InferVariants<RolesRoleTransformer>
    }
  }
  export namespace ScheduledEvents {
    export type ScheduledEvent = InferData<ScheduledEventsScheduledEventTransformer>
    export namespace ScheduledEvent {
      export type Variants = InferVariants<ScheduledEventsScheduledEventTransformer>
    }
  }
  export namespace Users {
    export type User = InferData<UsersUserTransformer>
    export namespace User {
      export type Variants = InferVariants<UsersUserTransformer>
    }
  }
  export type SharedProps = InferSharedProps<InertiaMiddleware>
}
