// @ts-nocheck
/* eslint-disable */
// --------------------------------------------------
// This file is auto-generated by Tuyau. Do not edit manually !
// --------------------------------------------------

import type { MakeTuyauRequest, MakeTuyauResponse } from '@tuyau/utils/types'
import type { InferInput } from '@vinejs/vine/types'

type ApiPaymentFleecaCallbackIdGetHead = {
  request: unknown
  response: MakeTuyauResponse<
    import('../app/core/controllers/payments_controller.ts').default['callback'],
    false
  >
}
type ApiAuthRedirectGtawGetHead = {
  request: unknown
  response: MakeTuyauResponse<
    import('../app/auth/controllers/auth_controller.ts').default['redirectToProvider'],
    false
  >
}
type ApiAuthCallbackGtawGetHead = {
  request: unknown
  response: MakeTuyauResponse<
    import('../app/auth/controllers/auth_controller.ts').default['handleCallback'],
    false
  >
}
type ApiAuthDeleteuserDelete = {
  request: unknown
  response: MakeTuyauResponse<
    import('../app/auth/controllers/auth_controller.ts').default['deleteUser'],
    false
  >
}
type ApiAuthLogoutPost = {
  request: unknown
  response: MakeTuyauResponse<
    import('../app/auth/controllers/auth_controller.ts').default['logout'],
    false
  >
}
type ApiAuthListcharactersGetHead = {
  request: unknown
  response: MakeTuyauResponse<
    import('../app/auth/controllers/characters_controller.ts').default['listCharacters'],
    false
  >
}
type ApiAuthCurrentcharacterPatch = {
  request: unknown
  response: MakeTuyauResponse<
    import('../app/auth/controllers/characters_controller.ts').default['switchCharacter'],
    false
  >
}
type DashboardGetHead = {
  request: unknown
  response: MakeTuyauResponse<
    import('../app/dashboard/controllers/pages_controller.ts').default['index'],
    false
  >
}
type DashboardArticlesGetHead = {
  request: unknown
  response: MakeTuyauResponse<
    import('../app/dashboard/controllers/articles_controller.ts').default['index'],
    false
  >
}
type DashboardArticlesCreateGetHead = {
  request: unknown
  response: MakeTuyauResponse<
    import('../app/dashboard/controllers/articles_controller.ts').default['create'],
    false
  >
}
type DashboardArticlesPost = {
  request: MakeTuyauRequest<
    InferInput<(typeof import('../app/dashboard/validators/article.ts'))['createArticleValidator']>
  >
  response: MakeTuyauResponse<
    import('../app/dashboard/controllers/articles_controller.ts').default['store'],
    true
  >
}
type DashboardArticlesIdGetHead = {
  request: unknown
  response: MakeTuyauResponse<
    import('../app/dashboard/controllers/articles_controller.ts').default['show'],
    false
  >
}
type DashboardArticlesIdEditGetHead = {
  request: unknown
  response: MakeTuyauResponse<
    import('../app/dashboard/controllers/articles_controller.ts').default['edit'],
    false
  >
}
type DashboardArticlesIdPutPatch = {
  request: MakeTuyauRequest<
    InferInput<(typeof import('../app/dashboard/validators/article.ts'))['updatedArticleValidator']>
  >
  response: MakeTuyauResponse<
    import('../app/dashboard/controllers/articles_controller.ts').default['update'],
    true
  >
}
type DashboardArticlesIdDelete = {
  request: unknown
  response: MakeTuyauResponse<
    import('../app/dashboard/controllers/articles_controller.ts').default['destroy'],
    false
  >
}
type DashboardEventsGetHead = {
  request: unknown
  response: MakeTuyauResponse<
    import('../app/dashboard/controllers/events_controller.ts').default['index'],
    false
  >
}
type DashboardEventsCreateGetHead = {
  request: unknown
  response: MakeTuyauResponse<
    import('../app/dashboard/controllers/events_controller.ts').default['create'],
    false
  >
}
type DashboardEventsPost = {
  request: MakeTuyauRequest<
    InferInput<(typeof import('../app/dashboard/validators/event.ts'))['createEventValidator']>
  >
  response: MakeTuyauResponse<
    import('../app/dashboard/controllers/events_controller.ts').default['store'],
    true
  >
}
type DashboardEventsIdGetHead = {
  request: unknown
  response: MakeTuyauResponse<
    import('../app/dashboard/controllers/events_controller.ts').default['show'],
    false
  >
}
type DashboardEventsIdEditGetHead = {
  request: unknown
  response: MakeTuyauResponse<
    import('../app/dashboard/controllers/events_controller.ts').default['edit'],
    false
  >
}
type DashboardEventsIdPutPatch = {
  request: MakeTuyauRequest<
    InferInput<(typeof import('../app/dashboard/validators/event.ts'))['updateEventValidator']>
  >
  response: MakeTuyauResponse<
    import('../app/dashboard/controllers/events_controller.ts').default['update'],
    true
  >
}
type DashboardEventsIdDelete = {
  request: unknown
  response: MakeTuyauResponse<
    import('../app/dashboard/controllers/events_controller.ts').default['destroy'],
    false
  >
}
type ContactGetHead = {
  request: unknown
  response: MakeTuyauResponse<
    import('../app/contact/controllers/contact_controller.ts').default['index'],
    false
  >
}
type ContactPost = {
  request: MakeTuyauRequest<
    InferInput<
      (typeof import('../app/contact/validators/contact_validation.ts'))['createContactValidator']
    >
  >
  response: MakeTuyauResponse<
    import('../app/contact/controllers/contact_controller.ts').default['submit'],
    true
  >
}
type NewsroomGetHead = {
  request: unknown
  response: MakeTuyauResponse<
    import('../app/news/controllers/news_controller.ts').default['index'],
    false
  >
}
type NewsroomIdGetHead = {
  request: unknown
  response: MakeTuyauResponse<
    import('../app/news/controllers/news_controller.ts').default['single'],
    false
  >
}
type FindGetHead = {
  request: unknown
  response: MakeTuyauResponse<
    import('../app/events/controllers/events_controller.ts').default['index'],
    false
  >
}
type FindEventsGetHead = {
  request: unknown
  response: MakeTuyauResponse<
    import('../app/events/controllers/events_controller.ts').default['index'],
    false
  >
}
type EventIdGetHead = {
  request: unknown
  response: MakeTuyauResponse<
    import('../app/events/controllers/events_controller.ts').default['single'],
    false
  >
}
type FindParishesGetHead = {
  request: unknown
  response: MakeTuyauResponse<
    import('../app/pages/controllers/parishes_controller.ts').default['parishes'],
    false
  >
}
type DepartmentsGetHead = {
  request: unknown
  response: MakeTuyauResponse<
    import('../app/pages/controllers/departments_controller.ts').default['index'],
    false
  >
}
type DepartmentIdGetHead = {
  request: unknown
  response: MakeTuyauResponse<
    import('../app/pages/controllers/departments_controller.ts').default['single'],
    false
  >
}
type ServicesGetHead = {
  request: unknown
  response: MakeTuyauResponse<
    import('../app/pages/controllers/services_controller.ts').default['index'],
    false
  >
}
type ServicesIdGetHead = {
  request: MakeTuyauRequest<
    InferInput<
      (typeof import('../app/pages/validators/service_slug.ts'))['createServiceSlugValidator']
    >
  >
  response: MakeTuyauResponse<
    import('../app/pages/controllers/services_controller.ts').default['single'],
    true
  >
}
type DonateGetHead = {
  request: unknown
  response: MakeTuyauResponse<
    import('../app/pages/controllers/donate_controller.ts').default['index'],
    false
  >
}
type DonatePost = {
  request: MakeTuyauRequest<
    InferInput<(typeof import('../app/pages/validators/donate.ts'))['createDonateFormValidator']>
  >
  response: MakeTuyauResponse<
    import('../app/pages/controllers/donate_controller.ts').default['submit'],
    true
  >
}
export interface ApiDefinition {
  api: {
    payment: {
      fleeca: {
        callback: {
          ':token': {
            $url: {}
            $get: ApiPaymentFleecaCallbackIdGetHead
            $head: ApiPaymentFleecaCallbackIdGetHead
          }
        }
      }
    }
    auth: {
      'redirect': {
        gtaw: {
          $url: {}
          $get: ApiAuthRedirectGtawGetHead
          $head: ApiAuthRedirectGtawGetHead
        }
      }
      'callback': {
        gtaw: {
          $url: {}
          $get: ApiAuthCallbackGtawGetHead
          $head: ApiAuthCallbackGtawGetHead
        }
      }
      'delete-user': {
        $url: {}
        $delete: ApiAuthDeleteuserDelete
      }
      'logout': {
        $url: {}
        $post: ApiAuthLogoutPost
      }
      'list-characters': {
        $url: {}
        $get: ApiAuthListcharactersGetHead
        $head: ApiAuthListcharactersGetHead
      }
      'current-character': {
        $url: {}
        $patch: ApiAuthCurrentcharacterPatch
      }
    }
  }
  dashboard: {
    $url: {}
    $get: DashboardGetHead
    $head: DashboardGetHead
    articles: {
      '$url': {}
      '$get': DashboardArticlesGetHead
      '$head': DashboardArticlesGetHead
      'create': {
        $url: {}
        $get: DashboardArticlesCreateGetHead
        $head: DashboardArticlesCreateGetHead
      }
      '$post': DashboardArticlesPost
      ':id': {
        $url: {}
        $get: DashboardArticlesIdGetHead
        $head: DashboardArticlesIdGetHead
        edit: {
          $url: {}
          $get: DashboardArticlesIdEditGetHead
          $head: DashboardArticlesIdEditGetHead
        }
        $put: DashboardArticlesIdPutPatch
        $patch: DashboardArticlesIdPutPatch
        $delete: DashboardArticlesIdDelete
      }
    }
    events: {
      '$url': {}
      '$get': DashboardEventsGetHead
      '$head': DashboardEventsGetHead
      'create': {
        $url: {}
        $get: DashboardEventsCreateGetHead
        $head: DashboardEventsCreateGetHead
      }
      '$post': DashboardEventsPost
      ':id': {
        $url: {}
        $get: DashboardEventsIdGetHead
        $head: DashboardEventsIdGetHead
        edit: {
          $url: {}
          $get: DashboardEventsIdEditGetHead
          $head: DashboardEventsIdEditGetHead
        }
        $put: DashboardEventsIdPutPatch
        $patch: DashboardEventsIdPutPatch
        $delete: DashboardEventsIdDelete
      }
    }
  }
  contact: {
    $url: {}
    $get: ContactGetHead
    $head: ContactGetHead
    $post: ContactPost
  }
  newsroom: {
    '$url': {}
    '$get': NewsroomGetHead
    '$head': NewsroomGetHead
    ':slug': {
      $url: {}
      $get: NewsroomIdGetHead
      $head: NewsroomIdGetHead
    }
  }
  find: {
    $url: {}
    $get: FindGetHead
    $head: FindGetHead
    events: {
      $url: {}
      $get: FindEventsGetHead
      $head: FindEventsGetHead
    }
    parishes: {
      $url: {}
      $get: FindParishesGetHead
      $head: FindParishesGetHead
    }
  }
  event: {
    ':slug': {
      $url: {}
      $get: EventIdGetHead
      $head: EventIdGetHead
    }
  }
  departments: {
    $url: {}
    $get: DepartmentsGetHead
    $head: DepartmentsGetHead
  }
  department: {
    ':slug': {
      $url: {}
      $get: DepartmentIdGetHead
      $head: DepartmentIdGetHead
    }
  }
  services: {
    '$url': {}
    '$get': ServicesGetHead
    '$head': ServicesGetHead
    ':slug': {
      $url: {}
      $get: ServicesIdGetHead
      $head: ServicesIdGetHead
    }
  }
  donate: {
    $url: {}
    $get: DonateGetHead
    $head: DonateGetHead
    $post: DonatePost
  }
}
const routes = [
  {
    params: ['token'],
    name: 'payment.callback',
    path: '/api/payment/fleeca/callback/:token',
    method: ['GET', 'HEAD'],
    types: {} as ApiPaymentFleecaCallbackIdGetHead,
  },
  {
    params: [],
    name: 'signIn',
    path: '/api/auth/redirect/gtaw',
    method: ['GET', 'HEAD'],
    types: {} as ApiAuthRedirectGtawGetHead,
  },
  {
    params: [],
    name: 'deleteUser',
    path: '/api/auth/delete-user',
    method: ['DELETE'],
    types: {} as ApiAuthDeleteuserDelete,
  },
  {
    params: [],
    name: 'logout',
    path: '/api/auth/logout',
    method: ['POST'],
    types: {} as ApiAuthLogoutPost,
  },
  {
    params: [],
    name: 'listCharacters',
    path: '/api/auth/list-characters',
    method: ['GET', 'HEAD'],
    types: {} as ApiAuthListcharactersGetHead,
  },
  {
    params: [],
    name: 'switchCharacter',
    path: '/api/auth/current-character',
    method: ['PATCH'],
    types: {} as ApiAuthCurrentcharacterPatch,
  },
  {
    params: [],
    name: 'profile',
    path: '/profile',
    method: ['GET', 'HEAD'],
    types: {} as unknown,
  },
  {
    params: [],
    name: 'dashboard.index',
    path: '/dashboard',
    method: ['GET', 'HEAD'],
    types: {} as DashboardGetHead,
  },
  {
    params: [],
    name: 'dashboard.dashboard_articles.index',
    path: '/dashboard/articles',
    method: ['GET', 'HEAD'],
    types: {} as DashboardArticlesGetHead,
  },
  {
    params: [],
    name: 'dashboard.dashboard_articles.create',
    path: '/dashboard/articles/create',
    method: ['GET', 'HEAD'],
    types: {} as DashboardArticlesCreateGetHead,
  },
  {
    params: [],
    name: 'dashboard.dashboard_articles.store',
    path: '/dashboard/articles',
    method: ['POST'],
    types: {} as DashboardArticlesPost,
  },
  {
    params: ['id'],
    name: 'dashboard.dashboard_articles.show',
    path: '/dashboard/articles/:id',
    method: ['GET', 'HEAD'],
    types: {} as DashboardArticlesIdGetHead,
  },
  {
    params: ['id'],
    name: 'dashboard.dashboard_articles.edit',
    path: '/dashboard/articles/:id/edit',
    method: ['GET', 'HEAD'],
    types: {} as DashboardArticlesIdEditGetHead,
  },
  {
    params: ['id'],
    name: 'dashboard.dashboard_articles.update',
    path: '/dashboard/articles/:id',
    method: ['PUT', 'PATCH'],
    types: {} as DashboardArticlesIdPutPatch,
  },
  {
    params: ['id'],
    name: 'dashboard.dashboard_articles.destroy',
    path: '/dashboard/articles/:id',
    method: ['DELETE'],
    types: {} as DashboardArticlesIdDelete,
  },
  {
    params: [],
    name: 'dashboard.dashboard_events.index',
    path: '/dashboard/events',
    method: ['GET', 'HEAD'],
    types: {} as DashboardEventsGetHead,
  },
  {
    params: [],
    name: 'dashboard.dashboard_events.create',
    path: '/dashboard/events/create',
    method: ['GET', 'HEAD'],
    types: {} as DashboardEventsCreateGetHead,
  },
  {
    params: [],
    name: 'dashboard.dashboard_events.store',
    path: '/dashboard/events',
    method: ['POST'],
    types: {} as DashboardEventsPost,
  },
  {
    params: ['id'],
    name: 'dashboard.dashboard_events.show',
    path: '/dashboard/events/:id',
    method: ['GET', 'HEAD'],
    types: {} as DashboardEventsIdGetHead,
  },
  {
    params: ['id'],
    name: 'dashboard.dashboard_events.edit',
    path: '/dashboard/events/:id/edit',
    method: ['GET', 'HEAD'],
    types: {} as DashboardEventsIdEditGetHead,
  },
  {
    params: ['id'],
    name: 'dashboard.dashboard_events.update',
    path: '/dashboard/events/:id',
    method: ['PUT', 'PATCH'],
    types: {} as DashboardEventsIdPutPatch,
  },
  {
    params: ['id'],
    name: 'dashboard.dashboard_events.destroy',
    path: '/dashboard/events/:id',
    method: ['DELETE'],
    types: {} as DashboardEventsIdDelete,
  },
  {
    params: [],
    name: 'home',
    path: '/',
    method: ['GET', 'HEAD'],
    types: {} as unknown,
  },
  {
    params: [],
    name: 'contact',
    path: '/contact',
    method: ['GET', 'HEAD'],
    types: {} as ContactGetHead,
  },
  {
    params: [],
    name: 'contact.submit',
    path: '/contact',
    method: ['POST'],
    types: {} as ContactPost,
  },
  {
    params: [],
    name: 'news.index',
    path: '/newsroom',
    method: ['GET', 'HEAD'],
    types: {} as NewsroomGetHead,
  },
  {
    params: ['slug'],
    name: 'news.single',
    path: '/newsroom/:slug',
    method: ['GET', 'HEAD'],
    types: {} as NewsroomIdGetHead,
  },
  {
    params: [],
    name: 'find.events',
    path: '/find/events',
    method: ['GET', 'HEAD'],
    types: {} as FindEventsGetHead,
  },
  {
    params: ['slug'],
    name: 'event',
    path: '/event/:slug',
    method: ['GET', 'HEAD'],
    types: {} as EventIdGetHead,
  },
  {
    params: [],
    name: 'find.parishes',
    path: '/find/parishes',
    method: ['GET', 'HEAD'],
    types: {} as FindParishesGetHead,
  },
  {
    params: [],
    name: 'about-us',
    path: '/about',
    method: ['GET', 'HEAD'],
    types: {} as unknown,
  },
  {
    params: [],
    name: 'archbishop.index',
    path: '/archbishop',
    method: ['GET', 'HEAD'],
    types: {} as unknown,
  },
  {
    params: [],
    name: 'departments.index',
    path: '/departments',
    method: ['GET', 'HEAD'],
    types: {} as DepartmentsGetHead,
  },
  {
    params: ['slug'],
    name: 'departments.single',
    path: '/department/:slug',
    method: ['GET', 'HEAD'],
    types: {} as DepartmentIdGetHead,
  },
  {
    params: [],
    name: 'services.index',
    path: '/services',
    method: ['GET', 'HEAD'],
    types: {} as ServicesGetHead,
  },
  {
    params: ['slug'],
    name: 'services.single',
    path: '/services/:slug',
    method: ['GET', 'HEAD'],
    types: {} as ServicesIdGetHead,
  },
  {
    params: [],
    name: 'donate.index',
    path: '/donate',
    method: ['GET', 'HEAD'],
    types: {} as DonateGetHead,
  },
  {
    params: [],
    name: 'donate.submit',
    path: '/donate',
    method: ['POST'],
    types: {} as DonatePost,
  },
  {
    params: [],
    name: 'privacy',
    path: '/privacy',
    method: ['GET', 'HEAD'],
    types: {} as unknown,
  },
  {
    params: [],
    name: 'charities.index',
    path: '/catholic-charities',
    method: ['GET', 'HEAD'],
    types: {} as unknown,
  },
  {
    params: [],
    name: 'vocations',
    path: '/vocations',
    method: ['GET', 'HEAD'],
    types: {} as unknown,
  },
  {
    params: [],
    name: 'jobs.index',
    path: '/jobs',
    method: ['GET', 'HEAD'],
    types: {} as unknown,
  },
  {
    params: [],
    name: 'dailyReadings',
    path: '/daily-readings',
    method: ['GET', 'HEAD'],
    types: {} as unknown,
  },
] as const
export const api = {
  routes,
  definition: {} as ApiDefinition,
}
declare module '@tuyau/inertia/types' {
  type InertiaApi = typeof api
  export interface Api extends InertiaApi {}
}
