/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/_app'
import { Route as DashboardRouteRouteImport } from './routes/dashboard/route'
import { Route as RobotsDottxtRouteImport } from './routes/robots[.]txt'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as AppIndexRouteImport } from './routes/_app/index'
import { Route as AppAboutRouteImport } from './routes/_app/about'
import { Route as AppAccountRouteRouteImport } from './routes/_app/account/route'
import { Route as AppArchbishopRouteImport } from './routes/_app/archbishop'
import { Route as AppCareersRouteImport } from './routes/_app/careers'
import { Route as AppCharitiesRouteRouteImport } from './routes/_app/charities/route'
import { Route as AppClergyApplicationRouteImport } from './routes/_app/clergy-application'
import { Route as AppContactRouteImport } from './routes/_app/contact'
import { Route as AppDailyReadingsRouteImport } from './routes/_app/daily-readings'
import { Route as AppDecreesRouteRouteImport } from './routes/_app/decrees/route'
import { Route as AppDepartmentsRouteImport } from './routes/_app/departments'
import { Route as AppDonateRouteImport } from './routes/_app/donate'
import { Route as AppEventsRouteImport } from './routes/_app/events'
import { Route as AppNewsroomRouteImport } from './routes/_app/newsroom'
import { Route as AppParishesRouteImport } from './routes/_app/parishes'
import { Route as AppPrivacyRouteImport } from './routes/_app/privacy'
import { Route as AppRegisterParishionerRouteImport } from './routes/_app/register-parishioner'
import { Route as AppServicesRouteImport } from './routes/_app/services'
import { Route as AppVocationsRouteImport } from './routes/_app/vocations'
import { Route as AppVolunteersRouteImport } from './routes/_app/volunteers'
import { Route as DashboardIndexRouteImport } from './routes/dashboard/index'
import { Route as DashboardUsersRouteRouteImport } from './routes/dashboard/users/route'
import { Route as AppAccountIndexRouteImport } from './routes/_app/account/index'
import { Route as AppAccountSessionsRouteImport } from './routes/_app/account/sessions'
import { Route as AppAccountSettingsRouteImport } from './routes/_app/account/settings'
import { Route as AppCharitiesIndexRouteImport } from './routes/_app/charities/index'
import { Route as AppDecreesIndexRouteImport } from './routes/_app/decrees/index'
import { Route as AppDecreesUidRouteImport } from './routes/_app/decrees/$uid'
import { Route as AppDepartmentSlugRouteImport } from './routes/_app/department/$slug'
import { Route as AppEventSlugRouteImport } from './routes/_app/event/$slug'
import { Route as AppPostSlugRouteImport } from './routes/_app/post/$slug'
import { Route as AppServiceSlugRouteImport } from './routes/_app/service/$slug'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as DashboardEventsIndexRouteImport } from './routes/dashboard/events/index'
import { Route as DashboardEventsCreateRouteImport } from './routes/dashboard/events/create'
import { Route as DashboardJobOpeningsIndexRouteImport } from './routes/dashboard/job-openings/index'
import { Route as DashboardJobOpeningsCreateRouteImport } from './routes/dashboard/job-openings/create'
import { Route as DashboardPostsIndexRouteImport } from './routes/dashboard/posts/index'
import { Route as DashboardPostsCreateRouteImport } from './routes/dashboard/posts/create'
import { Route as DashboardUsersIndexRouteImport } from './routes/dashboard/users/index'
import { Route as AppCharitiesProgramSlugRouteImport } from './routes/_app/charities/program/$slug'
import { Route as AppJobSlugIndexRouteImport } from './routes/_app/job/$slug.index'
import { Route as AppJobSlugApplyRouteImport } from './routes/_app/job/$slug.apply'
import { Route as ApiPaymentFleecaCallbackRouteImport } from './routes/api/payment/fleeca/callback'
import { Route as ApiPaymentFleecaWebhookRouteImport } from './routes/api/payment/fleeca/webhook'
import { Route as ApiPaymentStatusPaymentIdRouteImport } from './routes/api/payment/status/$paymentId'
import { Route as DashboardEventsEditIdRouteImport } from './routes/dashboard/events/edit.$id'
import { Route as DashboardEventsShowIdRouteImport } from './routes/dashboard/events/show.$id'
import { Route as DashboardJobOpeningsEditIdRouteImport } from './routes/dashboard/job-openings/edit.$id'
import { Route as DashboardJobOpeningsShowIdRouteImport } from './routes/dashboard/job-openings/show.$id'
import { Route as DashboardPostsEditIdRouteImport } from './routes/dashboard/posts/edit.$id'
import { Route as DashboardPostsShowIdRouteImport } from './routes/dashboard/posts/show.$id'
import { Route as DashboardUsersEditIdRouteImport } from './routes/dashboard/users/edit.$id'

const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRouteRoute = DashboardRouteRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const RobotsDottxtRoute = RobotsDottxtRouteImport.update({
  id: '/robots.txt',
  path: '/robots.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppAboutRoute = AppAboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => AppRoute,
} as any)
const AppAccountRouteRoute = AppAccountRouteRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => AppRoute,
} as any)
const AppArchbishopRoute = AppArchbishopRouteImport.update({
  id: '/archbishop',
  path: '/archbishop',
  getParentRoute: () => AppRoute,
} as any)
const AppCareersRoute = AppCareersRouteImport.update({
  id: '/careers',
  path: '/careers',
  getParentRoute: () => AppRoute,
} as any)
const AppCharitiesRouteRoute = AppCharitiesRouteRouteImport.update({
  id: '/charities',
  path: '/charities',
  getParentRoute: () => AppRoute,
} as any)
const AppClergyApplicationRoute = AppClergyApplicationRouteImport.update({
  id: '/clergy-application',
  path: '/clergy-application',
  getParentRoute: () => AppRoute,
} as any)
const AppContactRoute = AppContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => AppRoute,
} as any)
const AppDailyReadingsRoute = AppDailyReadingsRouteImport.update({
  id: '/daily-readings',
  path: '/daily-readings',
  getParentRoute: () => AppRoute,
} as any)
const AppDecreesRouteRoute = AppDecreesRouteRouteImport.update({
  id: '/decrees',
  path: '/decrees',
  getParentRoute: () => AppRoute,
} as any)
const AppDepartmentsRoute = AppDepartmentsRouteImport.update({
  id: '/departments',
  path: '/departments',
  getParentRoute: () => AppRoute,
} as any)
const AppDonateRoute = AppDonateRouteImport.update({
  id: '/donate',
  path: '/donate',
  getParentRoute: () => AppRoute,
} as any)
const AppEventsRoute = AppEventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => AppRoute,
} as any)
const AppNewsroomRoute = AppNewsroomRouteImport.update({
  id: '/newsroom',
  path: '/newsroom',
  getParentRoute: () => AppRoute,
} as any)
const AppParishesRoute = AppParishesRouteImport.update({
  id: '/parishes',
  path: '/parishes',
  getParentRoute: () => AppRoute,
} as any)
const AppPrivacyRoute = AppPrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => AppRoute,
} as any)
const AppRegisterParishionerRoute = AppRegisterParishionerRouteImport.update({
  id: '/register-parishioner',
  path: '/register-parishioner',
  getParentRoute: () => AppRoute,
} as any)
const AppServicesRoute = AppServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => AppRoute,
} as any)
const AppVocationsRoute = AppVocationsRouteImport.update({
  id: '/vocations',
  path: '/vocations',
  getParentRoute: () => AppRoute,
} as any)
const AppVolunteersRoute = AppVolunteersRouteImport.update({
  id: '/volunteers',
  path: '/volunteers',
  getParentRoute: () => AppRoute,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardUsersRouteRoute = DashboardUsersRouteRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const AppAccountIndexRoute = AppAccountIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppAccountRouteRoute,
} as any)
const AppAccountSessionsRoute = AppAccountSessionsRouteImport.update({
  id: '/sessions',
  path: '/sessions',
  getParentRoute: () => AppAccountRouteRoute,
} as any)
const AppAccountSettingsRoute = AppAccountSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppAccountRouteRoute,
} as any)
const AppCharitiesIndexRoute = AppCharitiesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppCharitiesRouteRoute,
} as any)
const AppDecreesIndexRoute = AppDecreesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppDecreesRouteRoute,
} as any)
const AppDecreesUidRoute = AppDecreesUidRouteImport.update({
  id: '/$uid',
  path: '/$uid',
  getParentRoute: () => AppDecreesRouteRoute,
} as any)
const AppDepartmentSlugRoute = AppDepartmentSlugRouteImport.update({
  id: '/department/$slug',
  path: '/department/$slug',
  getParentRoute: () => AppRoute,
} as any)
const AppEventSlugRoute = AppEventSlugRouteImport.update({
  id: '/event/$slug',
  path: '/event/$slug',
  getParentRoute: () => AppRoute,
} as any)
const AppPostSlugRoute = AppPostSlugRouteImport.update({
  id: '/post/$slug',
  path: '/post/$slug',
  getParentRoute: () => AppRoute,
} as any)
const AppServiceSlugRoute = AppServiceSlugRouteImport.update({
  id: '/service/$slug',
  path: '/service/$slug',
  getParentRoute: () => AppRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardEventsIndexRoute = DashboardEventsIndexRouteImport.update({
  id: '/events/',
  path: '/events/',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardEventsCreateRoute = DashboardEventsCreateRouteImport.update({
  id: '/events/create',
  path: '/events/create',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardJobOpeningsIndexRoute =
  DashboardJobOpeningsIndexRouteImport.update({
    id: '/job-openings/',
    path: '/job-openings/',
    getParentRoute: () => DashboardRouteRoute,
  } as any)
const DashboardJobOpeningsCreateRoute =
  DashboardJobOpeningsCreateRouteImport.update({
    id: '/job-openings/create',
    path: '/job-openings/create',
    getParentRoute: () => DashboardRouteRoute,
  } as any)
const DashboardPostsIndexRoute = DashboardPostsIndexRouteImport.update({
  id: '/posts/',
  path: '/posts/',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardPostsCreateRoute = DashboardPostsCreateRouteImport.update({
  id: '/posts/create',
  path: '/posts/create',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardUsersIndexRoute = DashboardUsersIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardUsersRouteRoute,
} as any)
const AppCharitiesProgramSlugRoute = AppCharitiesProgramSlugRouteImport.update({
  id: '/program/$slug',
  path: '/program/$slug',
  getParentRoute: () => AppCharitiesRouteRoute,
} as any)
const AppJobSlugIndexRoute = AppJobSlugIndexRouteImport.update({
  id: '/job/$slug/',
  path: '/job/$slug/',
  getParentRoute: () => AppRoute,
} as any)
const AppJobSlugApplyRoute = AppJobSlugApplyRouteImport.update({
  id: '/job/$slug/apply',
  path: '/job/$slug/apply',
  getParentRoute: () => AppRoute,
} as any)
const ApiPaymentFleecaCallbackRoute =
  ApiPaymentFleecaCallbackRouteImport.update({
    id: '/api/payment/fleeca/callback',
    path: '/api/payment/fleeca/callback',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPaymentFleecaWebhookRoute = ApiPaymentFleecaWebhookRouteImport.update({
  id: '/api/payment/fleeca/webhook',
  path: '/api/payment/fleeca/webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPaymentStatusPaymentIdRoute =
  ApiPaymentStatusPaymentIdRouteImport.update({
    id: '/api/payment/status/$paymentId',
    path: '/api/payment/status/$paymentId',
    getParentRoute: () => rootRouteImport,
  } as any)
const DashboardEventsEditIdRoute = DashboardEventsEditIdRouteImport.update({
  id: '/events/edit/$id',
  path: '/events/edit/$id',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardEventsShowIdRoute = DashboardEventsShowIdRouteImport.update({
  id: '/events/show/$id',
  path: '/events/show/$id',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardJobOpeningsEditIdRoute =
  DashboardJobOpeningsEditIdRouteImport.update({
    id: '/job-openings/edit/$id',
    path: '/job-openings/edit/$id',
    getParentRoute: () => DashboardRouteRoute,
  } as any)
const DashboardJobOpeningsShowIdRoute =
  DashboardJobOpeningsShowIdRouteImport.update({
    id: '/job-openings/show/$id',
    path: '/job-openings/show/$id',
    getParentRoute: () => DashboardRouteRoute,
  } as any)
const DashboardPostsEditIdRoute = DashboardPostsEditIdRouteImport.update({
  id: '/posts/edit/$id',
  path: '/posts/edit/$id',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardPostsShowIdRoute = DashboardPostsShowIdRouteImport.update({
  id: '/posts/show/$id',
  path: '/posts/show/$id',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardUsersEditIdRoute = DashboardUsersEditIdRouteImport.update({
  id: '/edit/$id',
  path: '/edit/$id',
  getParentRoute: () => DashboardUsersRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/dashboard': typeof DashboardRouteRouteWithChildren
  '/': typeof AppIndexRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/account': typeof AppAccountRouteRouteWithChildren
  '/charities': typeof AppCharitiesRouteRouteWithChildren
  '/decrees': typeof AppDecreesRouteRouteWithChildren
  '/dashboard/users': typeof DashboardUsersRouteRouteWithChildren
  '/about': typeof AppAboutRoute
  '/archbishop': typeof AppArchbishopRoute
  '/careers': typeof AppCareersRoute
  '/clergy-application': typeof AppClergyApplicationRoute
  '/contact': typeof AppContactRoute
  '/daily-readings': typeof AppDailyReadingsRoute
  '/departments': typeof AppDepartmentsRoute
  '/donate': typeof AppDonateRoute
  '/events': typeof AppEventsRoute
  '/newsroom': typeof AppNewsroomRoute
  '/parishes': typeof AppParishesRoute
  '/privacy': typeof AppPrivacyRoute
  '/register-parishioner': typeof AppRegisterParishionerRoute
  '/services': typeof AppServicesRoute
  '/vocations': typeof AppVocationsRoute
  '/volunteers': typeof AppVolunteersRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/account/sessions': typeof AppAccountSessionsRoute
  '/account/settings': typeof AppAccountSettingsRoute
  '/decrees/$uid': typeof AppDecreesUidRoute
  '/department/$slug': typeof AppDepartmentSlugRoute
  '/event/$slug': typeof AppEventSlugRoute
  '/post/$slug': typeof AppPostSlugRoute
  '/service/$slug': typeof AppServiceSlugRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/dashboard/events/create': typeof DashboardEventsCreateRoute
  '/dashboard/job-openings/create': typeof DashboardJobOpeningsCreateRoute
  '/dashboard/posts/create': typeof DashboardPostsCreateRoute
  '/account/': typeof AppAccountIndexRoute
  '/charities/': typeof AppCharitiesIndexRoute
  '/decrees/': typeof AppDecreesIndexRoute
  '/dashboard/events/': typeof DashboardEventsIndexRoute
  '/dashboard/job-openings/': typeof DashboardJobOpeningsIndexRoute
  '/dashboard/posts/': typeof DashboardPostsIndexRoute
  '/dashboard/users/': typeof DashboardUsersIndexRoute
  '/charities/program/$slug': typeof AppCharitiesProgramSlugRoute
  '/job/$slug/apply': typeof AppJobSlugApplyRoute
  '/api/payment/fleeca/callback': typeof ApiPaymentFleecaCallbackRoute
  '/api/payment/fleeca/webhook': typeof ApiPaymentFleecaWebhookRoute
  '/api/payment/status/$paymentId': typeof ApiPaymentStatusPaymentIdRoute
  '/dashboard/events/edit/$id': typeof DashboardEventsEditIdRoute
  '/dashboard/events/show/$id': typeof DashboardEventsShowIdRoute
  '/dashboard/job-openings/edit/$id': typeof DashboardJobOpeningsEditIdRoute
  '/dashboard/job-openings/show/$id': typeof DashboardJobOpeningsShowIdRoute
  '/dashboard/posts/edit/$id': typeof DashboardPostsEditIdRoute
  '/dashboard/posts/show/$id': typeof DashboardPostsShowIdRoute
  '/dashboard/users/edit/$id': typeof DashboardUsersEditIdRoute
  '/job/$slug/': typeof AppJobSlugIndexRoute
}
export interface FileRoutesByTo {
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/about': typeof AppAboutRoute
  '/archbishop': typeof AppArchbishopRoute
  '/careers': typeof AppCareersRoute
  '/clergy-application': typeof AppClergyApplicationRoute
  '/contact': typeof AppContactRoute
  '/daily-readings': typeof AppDailyReadingsRoute
  '/departments': typeof AppDepartmentsRoute
  '/donate': typeof AppDonateRoute
  '/events': typeof AppEventsRoute
  '/newsroom': typeof AppNewsroomRoute
  '/parishes': typeof AppParishesRoute
  '/privacy': typeof AppPrivacyRoute
  '/register-parishioner': typeof AppRegisterParishionerRoute
  '/services': typeof AppServicesRoute
  '/vocations': typeof AppVocationsRoute
  '/volunteers': typeof AppVolunteersRoute
  '/': typeof AppIndexRoute
  '/dashboard': typeof DashboardIndexRoute
  '/account/sessions': typeof AppAccountSessionsRoute
  '/account/settings': typeof AppAccountSettingsRoute
  '/decrees/$uid': typeof AppDecreesUidRoute
  '/department/$slug': typeof AppDepartmentSlugRoute
  '/event/$slug': typeof AppEventSlugRoute
  '/post/$slug': typeof AppPostSlugRoute
  '/service/$slug': typeof AppServiceSlugRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/dashboard/events/create': typeof DashboardEventsCreateRoute
  '/dashboard/job-openings/create': typeof DashboardJobOpeningsCreateRoute
  '/dashboard/posts/create': typeof DashboardPostsCreateRoute
  '/account': typeof AppAccountIndexRoute
  '/charities': typeof AppCharitiesIndexRoute
  '/decrees': typeof AppDecreesIndexRoute
  '/dashboard/events': typeof DashboardEventsIndexRoute
  '/dashboard/job-openings': typeof DashboardJobOpeningsIndexRoute
  '/dashboard/posts': typeof DashboardPostsIndexRoute
  '/dashboard/users': typeof DashboardUsersIndexRoute
  '/charities/program/$slug': typeof AppCharitiesProgramSlugRoute
  '/job/$slug/apply': typeof AppJobSlugApplyRoute
  '/api/payment/fleeca/callback': typeof ApiPaymentFleecaCallbackRoute
  '/api/payment/fleeca/webhook': typeof ApiPaymentFleecaWebhookRoute
  '/api/payment/status/$paymentId': typeof ApiPaymentStatusPaymentIdRoute
  '/dashboard/events/edit/$id': typeof DashboardEventsEditIdRoute
  '/dashboard/events/show/$id': typeof DashboardEventsShowIdRoute
  '/dashboard/job-openings/edit/$id': typeof DashboardJobOpeningsEditIdRoute
  '/dashboard/job-openings/show/$id': typeof DashboardJobOpeningsShowIdRoute
  '/dashboard/posts/edit/$id': typeof DashboardPostsEditIdRoute
  '/dashboard/posts/show/$id': typeof DashboardPostsShowIdRoute
  '/dashboard/users/edit/$id': typeof DashboardUsersEditIdRoute
  '/job/$slug': typeof AppJobSlugIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/dashboard': typeof DashboardRouteRouteWithChildren
  '/_app': typeof AppRouteWithChildren
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/_app/account': typeof AppAccountRouteRouteWithChildren
  '/_app/charities': typeof AppCharitiesRouteRouteWithChildren
  '/_app/decrees': typeof AppDecreesRouteRouteWithChildren
  '/dashboard/users': typeof DashboardUsersRouteRouteWithChildren
  '/_app/about': typeof AppAboutRoute
  '/_app/archbishop': typeof AppArchbishopRoute
  '/_app/careers': typeof AppCareersRoute
  '/_app/clergy-application': typeof AppClergyApplicationRoute
  '/_app/contact': typeof AppContactRoute
  '/_app/daily-readings': typeof AppDailyReadingsRoute
  '/_app/departments': typeof AppDepartmentsRoute
  '/_app/donate': typeof AppDonateRoute
  '/_app/events': typeof AppEventsRoute
  '/_app/newsroom': typeof AppNewsroomRoute
  '/_app/parishes': typeof AppParishesRoute
  '/_app/privacy': typeof AppPrivacyRoute
  '/_app/register-parishioner': typeof AppRegisterParishionerRoute
  '/_app/services': typeof AppServicesRoute
  '/_app/vocations': typeof AppVocationsRoute
  '/_app/volunteers': typeof AppVolunteersRoute
  '/_app/': typeof AppIndexRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/_app/account/sessions': typeof AppAccountSessionsRoute
  '/_app/account/settings': typeof AppAccountSettingsRoute
  '/_app/decrees/$uid': typeof AppDecreesUidRoute
  '/_app/department/$slug': typeof AppDepartmentSlugRoute
  '/_app/event/$slug': typeof AppEventSlugRoute
  '/_app/post/$slug': typeof AppPostSlugRoute
  '/_app/service/$slug': typeof AppServiceSlugRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/dashboard/events/create': typeof DashboardEventsCreateRoute
  '/dashboard/job-openings/create': typeof DashboardJobOpeningsCreateRoute
  '/dashboard/posts/create': typeof DashboardPostsCreateRoute
  '/_app/account/': typeof AppAccountIndexRoute
  '/_app/charities/': typeof AppCharitiesIndexRoute
  '/_app/decrees/': typeof AppDecreesIndexRoute
  '/dashboard/events/': typeof DashboardEventsIndexRoute
  '/dashboard/job-openings/': typeof DashboardJobOpeningsIndexRoute
  '/dashboard/posts/': typeof DashboardPostsIndexRoute
  '/dashboard/users/': typeof DashboardUsersIndexRoute
  '/_app/charities/program/$slug': typeof AppCharitiesProgramSlugRoute
  '/_app/job/$slug/apply': typeof AppJobSlugApplyRoute
  '/api/payment/fleeca/callback': typeof ApiPaymentFleecaCallbackRoute
  '/api/payment/fleeca/webhook': typeof ApiPaymentFleecaWebhookRoute
  '/api/payment/status/$paymentId': typeof ApiPaymentStatusPaymentIdRoute
  '/dashboard/events/edit/$id': typeof DashboardEventsEditIdRoute
  '/dashboard/events/show/$id': typeof DashboardEventsShowIdRoute
  '/dashboard/job-openings/edit/$id': typeof DashboardJobOpeningsEditIdRoute
  '/dashboard/job-openings/show/$id': typeof DashboardJobOpeningsShowIdRoute
  '/dashboard/posts/edit/$id': typeof DashboardPostsEditIdRoute
  '/dashboard/posts/show/$id': typeof DashboardPostsShowIdRoute
  '/dashboard/users/edit/$id': typeof DashboardUsersEditIdRoute
  '/_app/job/$slug/': typeof AppJobSlugIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/dashboard'
    | '/'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/account'
    | '/charities'
    | '/decrees'
    | '/dashboard/users'
    | '/about'
    | '/archbishop'
    | '/careers'
    | '/clergy-application'
    | '/contact'
    | '/daily-readings'
    | '/departments'
    | '/donate'
    | '/events'
    | '/newsroom'
    | '/parishes'
    | '/privacy'
    | '/register-parishioner'
    | '/services'
    | '/vocations'
    | '/volunteers'
    | '/dashboard/'
    | '/account/sessions'
    | '/account/settings'
    | '/decrees/$uid'
    | '/department/$slug'
    | '/event/$slug'
    | '/post/$slug'
    | '/service/$slug'
    | '/api/auth/$'
    | '/dashboard/events/create'
    | '/dashboard/job-openings/create'
    | '/dashboard/posts/create'
    | '/account/'
    | '/charities/'
    | '/decrees/'
    | '/dashboard/events/'
    | '/dashboard/job-openings/'
    | '/dashboard/posts/'
    | '/dashboard/users/'
    | '/charities/program/$slug'
    | '/job/$slug/apply'
    | '/api/payment/fleeca/callback'
    | '/api/payment/fleeca/webhook'
    | '/api/payment/status/$paymentId'
    | '/dashboard/events/edit/$id'
    | '/dashboard/events/show/$id'
    | '/dashboard/job-openings/edit/$id'
    | '/dashboard/job-openings/show/$id'
    | '/dashboard/posts/edit/$id'
    | '/dashboard/posts/show/$id'
    | '/dashboard/users/edit/$id'
    | '/job/$slug/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/robots.txt'
    | '/sitemap.xml'
    | '/about'
    | '/archbishop'
    | '/careers'
    | '/clergy-application'
    | '/contact'
    | '/daily-readings'
    | '/departments'
    | '/donate'
    | '/events'
    | '/newsroom'
    | '/parishes'
    | '/privacy'
    | '/register-parishioner'
    | '/services'
    | '/vocations'
    | '/volunteers'
    | '/'
    | '/dashboard'
    | '/account/sessions'
    | '/account/settings'
    | '/decrees/$uid'
    | '/department/$slug'
    | '/event/$slug'
    | '/post/$slug'
    | '/service/$slug'
    | '/api/auth/$'
    | '/dashboard/events/create'
    | '/dashboard/job-openings/create'
    | '/dashboard/posts/create'
    | '/account'
    | '/charities'
    | '/decrees'
    | '/dashboard/events'
    | '/dashboard/job-openings'
    | '/dashboard/posts'
    | '/dashboard/users'
    | '/charities/program/$slug'
    | '/job/$slug/apply'
    | '/api/payment/fleeca/callback'
    | '/api/payment/fleeca/webhook'
    | '/api/payment/status/$paymentId'
    | '/dashboard/events/edit/$id'
    | '/dashboard/events/show/$id'
    | '/dashboard/job-openings/edit/$id'
    | '/dashboard/job-openings/show/$id'
    | '/dashboard/posts/edit/$id'
    | '/dashboard/posts/show/$id'
    | '/dashboard/users/edit/$id'
    | '/job/$slug'
  id:
    | '__root__'
    | '/dashboard'
    | '/_app'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/_app/account'
    | '/_app/charities'
    | '/_app/decrees'
    | '/dashboard/users'
    | '/_app/about'
    | '/_app/archbishop'
    | '/_app/careers'
    | '/_app/clergy-application'
    | '/_app/contact'
    | '/_app/daily-readings'
    | '/_app/departments'
    | '/_app/donate'
    | '/_app/events'
    | '/_app/newsroom'
    | '/_app/parishes'
    | '/_app/privacy'
    | '/_app/register-parishioner'
    | '/_app/services'
    | '/_app/vocations'
    | '/_app/volunteers'
    | '/_app/'
    | '/dashboard/'
    | '/_app/account/sessions'
    | '/_app/account/settings'
    | '/_app/decrees/$uid'
    | '/_app/department/$slug'
    | '/_app/event/$slug'
    | '/_app/post/$slug'
    | '/_app/service/$slug'
    | '/api/auth/$'
    | '/dashboard/events/create'
    | '/dashboard/job-openings/create'
    | '/dashboard/posts/create'
    | '/_app/account/'
    | '/_app/charities/'
    | '/_app/decrees/'
    | '/dashboard/events/'
    | '/dashboard/job-openings/'
    | '/dashboard/posts/'
    | '/dashboard/users/'
    | '/_app/charities/program/$slug'
    | '/_app/job/$slug/apply'
    | '/api/payment/fleeca/callback'
    | '/api/payment/fleeca/webhook'
    | '/api/payment/status/$paymentId'
    | '/dashboard/events/edit/$id'
    | '/dashboard/events/show/$id'
    | '/dashboard/job-openings/edit/$id'
    | '/dashboard/job-openings/show/$id'
    | '/dashboard/posts/edit/$id'
    | '/dashboard/posts/show/$id'
    | '/dashboard/users/edit/$id'
    | '/_app/job/$slug/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  DashboardRouteRoute: typeof DashboardRouteRouteWithChildren
  AppRoute: typeof AppRouteWithChildren
  RobotsDottxtRoute: typeof RobotsDottxtRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiPaymentFleecaCallbackRoute: typeof ApiPaymentFleecaCallbackRoute
  ApiPaymentFleecaWebhookRoute: typeof ApiPaymentFleecaWebhookRoute
  ApiPaymentStatusPaymentIdRoute: typeof ApiPaymentStatusPaymentIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/robots.txt': {
      id: '/robots.txt'
      path: '/robots.txt'
      fullPath: '/robots.txt'
      preLoaderRoute: typeof RobotsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/about': {
      id: '/_app/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AppAboutRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/account': {
      id: '/_app/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AppAccountRouteRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/archbishop': {
      id: '/_app/archbishop'
      path: '/archbishop'
      fullPath: '/archbishop'
      preLoaderRoute: typeof AppArchbishopRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/careers': {
      id: '/_app/careers'
      path: '/careers'
      fullPath: '/careers'
      preLoaderRoute: typeof AppCareersRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/charities': {
      id: '/_app/charities'
      path: '/charities'
      fullPath: '/charities'
      preLoaderRoute: typeof AppCharitiesRouteRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/clergy-application': {
      id: '/_app/clergy-application'
      path: '/clergy-application'
      fullPath: '/clergy-application'
      preLoaderRoute: typeof AppClergyApplicationRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/contact': {
      id: '/_app/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof AppContactRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/daily-readings': {
      id: '/_app/daily-readings'
      path: '/daily-readings'
      fullPath: '/daily-readings'
      preLoaderRoute: typeof AppDailyReadingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/decrees': {
      id: '/_app/decrees'
      path: '/decrees'
      fullPath: '/decrees'
      preLoaderRoute: typeof AppDecreesRouteRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/departments': {
      id: '/_app/departments'
      path: '/departments'
      fullPath: '/departments'
      preLoaderRoute: typeof AppDepartmentsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/donate': {
      id: '/_app/donate'
      path: '/donate'
      fullPath: '/donate'
      preLoaderRoute: typeof AppDonateRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/events': {
      id: '/_app/events'
      path: '/events'
      fullPath: '/events'
      preLoaderRoute: typeof AppEventsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/newsroom': {
      id: '/_app/newsroom'
      path: '/newsroom'
      fullPath: '/newsroom'
      preLoaderRoute: typeof AppNewsroomRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/parishes': {
      id: '/_app/parishes'
      path: '/parishes'
      fullPath: '/parishes'
      preLoaderRoute: typeof AppParishesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/privacy': {
      id: '/_app/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof AppPrivacyRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/register-parishioner': {
      id: '/_app/register-parishioner'
      path: '/register-parishioner'
      fullPath: '/register-parishioner'
      preLoaderRoute: typeof AppRegisterParishionerRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/services': {
      id: '/_app/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof AppServicesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/vocations': {
      id: '/_app/vocations'
      path: '/vocations'
      fullPath: '/vocations'
      preLoaderRoute: typeof AppVocationsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/volunteers': {
      id: '/_app/volunteers'
      path: '/volunteers'
      fullPath: '/volunteers'
      preLoaderRoute: typeof AppVolunteersRouteImport
      parentRoute: typeof AppRoute
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/users': {
      id: '/dashboard/users'
      path: '/users'
      fullPath: '/dashboard/users'
      preLoaderRoute: typeof DashboardUsersRouteRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/_app/account/': {
      id: '/_app/account/'
      path: '/'
      fullPath: '/account/'
      preLoaderRoute: typeof AppAccountIndexRouteImport
      parentRoute: typeof AppAccountRouteRoute
    }
    '/_app/account/sessions': {
      id: '/_app/account/sessions'
      path: '/sessions'
      fullPath: '/account/sessions'
      preLoaderRoute: typeof AppAccountSessionsRouteImport
      parentRoute: typeof AppAccountRouteRoute
    }
    '/_app/account/settings': {
      id: '/_app/account/settings'
      path: '/settings'
      fullPath: '/account/settings'
      preLoaderRoute: typeof AppAccountSettingsRouteImport
      parentRoute: typeof AppAccountRouteRoute
    }
    '/_app/charities/': {
      id: '/_app/charities/'
      path: '/'
      fullPath: '/charities/'
      preLoaderRoute: typeof AppCharitiesIndexRouteImport
      parentRoute: typeof AppCharitiesRouteRoute
    }
    '/_app/decrees/': {
      id: '/_app/decrees/'
      path: '/'
      fullPath: '/decrees/'
      preLoaderRoute: typeof AppDecreesIndexRouteImport
      parentRoute: typeof AppDecreesRouteRoute
    }
    '/_app/decrees/$uid': {
      id: '/_app/decrees/$uid'
      path: '/$uid'
      fullPath: '/decrees/$uid'
      preLoaderRoute: typeof AppDecreesUidRouteImport
      parentRoute: typeof AppDecreesRouteRoute
    }
    '/_app/department/$slug': {
      id: '/_app/department/$slug'
      path: '/department/$slug'
      fullPath: '/department/$slug'
      preLoaderRoute: typeof AppDepartmentSlugRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/event/$slug': {
      id: '/_app/event/$slug'
      path: '/event/$slug'
      fullPath: '/event/$slug'
      preLoaderRoute: typeof AppEventSlugRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/post/$slug': {
      id: '/_app/post/$slug'
      path: '/post/$slug'
      fullPath: '/post/$slug'
      preLoaderRoute: typeof AppPostSlugRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/service/$slug': {
      id: '/_app/service/$slug'
      path: '/service/$slug'
      fullPath: '/service/$slug'
      preLoaderRoute: typeof AppServiceSlugRouteImport
      parentRoute: typeof AppRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/events/': {
      id: '/dashboard/events/'
      path: '/events'
      fullPath: '/dashboard/events/'
      preLoaderRoute: typeof DashboardEventsIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/events/create': {
      id: '/dashboard/events/create'
      path: '/events/create'
      fullPath: '/dashboard/events/create'
      preLoaderRoute: typeof DashboardEventsCreateRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/job-openings/': {
      id: '/dashboard/job-openings/'
      path: '/job-openings'
      fullPath: '/dashboard/job-openings/'
      preLoaderRoute: typeof DashboardJobOpeningsIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/job-openings/create': {
      id: '/dashboard/job-openings/create'
      path: '/job-openings/create'
      fullPath: '/dashboard/job-openings/create'
      preLoaderRoute: typeof DashboardJobOpeningsCreateRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/posts/': {
      id: '/dashboard/posts/'
      path: '/posts'
      fullPath: '/dashboard/posts/'
      preLoaderRoute: typeof DashboardPostsIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/posts/create': {
      id: '/dashboard/posts/create'
      path: '/posts/create'
      fullPath: '/dashboard/posts/create'
      preLoaderRoute: typeof DashboardPostsCreateRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/users/': {
      id: '/dashboard/users/'
      path: '/'
      fullPath: '/dashboard/users/'
      preLoaderRoute: typeof DashboardUsersIndexRouteImport
      parentRoute: typeof DashboardUsersRouteRoute
    }
    '/_app/charities/program/$slug': {
      id: '/_app/charities/program/$slug'
      path: '/program/$slug'
      fullPath: '/charities/program/$slug'
      preLoaderRoute: typeof AppCharitiesProgramSlugRouteImport
      parentRoute: typeof AppCharitiesRouteRoute
    }
    '/_app/job/$slug/': {
      id: '/_app/job/$slug/'
      path: '/job/$slug'
      fullPath: '/job/$slug/'
      preLoaderRoute: typeof AppJobSlugIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/job/$slug/apply': {
      id: '/_app/job/$slug/apply'
      path: '/job/$slug/apply'
      fullPath: '/job/$slug/apply'
      preLoaderRoute: typeof AppJobSlugApplyRouteImport
      parentRoute: typeof AppRoute
    }
    '/api/payment/fleeca/callback': {
      id: '/api/payment/fleeca/callback'
      path: '/api/payment/fleeca/callback'
      fullPath: '/api/payment/fleeca/callback'
      preLoaderRoute: typeof ApiPaymentFleecaCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/payment/fleeca/webhook': {
      id: '/api/payment/fleeca/webhook'
      path: '/api/payment/fleeca/webhook'
      fullPath: '/api/payment/fleeca/webhook'
      preLoaderRoute: typeof ApiPaymentFleecaWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/payment/status/$paymentId': {
      id: '/api/payment/status/$paymentId'
      path: '/api/payment/status/$paymentId'
      fullPath: '/api/payment/status/$paymentId'
      preLoaderRoute: typeof ApiPaymentStatusPaymentIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/events/edit/$id': {
      id: '/dashboard/events/edit/$id'
      path: '/events/edit/$id'
      fullPath: '/dashboard/events/edit/$id'
      preLoaderRoute: typeof DashboardEventsEditIdRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/events/show/$id': {
      id: '/dashboard/events/show/$id'
      path: '/events/show/$id'
      fullPath: '/dashboard/events/show/$id'
      preLoaderRoute: typeof DashboardEventsShowIdRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/job-openings/edit/$id': {
      id: '/dashboard/job-openings/edit/$id'
      path: '/job-openings/edit/$id'
      fullPath: '/dashboard/job-openings/edit/$id'
      preLoaderRoute: typeof DashboardJobOpeningsEditIdRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/job-openings/show/$id': {
      id: '/dashboard/job-openings/show/$id'
      path: '/job-openings/show/$id'
      fullPath: '/dashboard/job-openings/show/$id'
      preLoaderRoute: typeof DashboardJobOpeningsShowIdRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/posts/edit/$id': {
      id: '/dashboard/posts/edit/$id'
      path: '/posts/edit/$id'
      fullPath: '/dashboard/posts/edit/$id'
      preLoaderRoute: typeof DashboardPostsEditIdRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/posts/show/$id': {
      id: '/dashboard/posts/show/$id'
      path: '/posts/show/$id'
      fullPath: '/dashboard/posts/show/$id'
      preLoaderRoute: typeof DashboardPostsShowIdRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/users/edit/$id': {
      id: '/dashboard/users/edit/$id'
      path: '/edit/$id'
      fullPath: '/dashboard/users/edit/$id'
      preLoaderRoute: typeof DashboardUsersEditIdRouteImport
      parentRoute: typeof DashboardUsersRouteRoute
    }
  }
}

interface DashboardUsersRouteRouteChildren {
  DashboardUsersIndexRoute: typeof DashboardUsersIndexRoute
  DashboardUsersEditIdRoute: typeof DashboardUsersEditIdRoute
}

const DashboardUsersRouteRouteChildren: DashboardUsersRouteRouteChildren = {
  DashboardUsersIndexRoute: DashboardUsersIndexRoute,
  DashboardUsersEditIdRoute: DashboardUsersEditIdRoute,
}

const DashboardUsersRouteRouteWithChildren =
  DashboardUsersRouteRoute._addFileChildren(DashboardUsersRouteRouteChildren)

interface DashboardRouteRouteChildren {
  DashboardUsersRouteRoute: typeof DashboardUsersRouteRouteWithChildren
  DashboardIndexRoute: typeof DashboardIndexRoute
  DashboardEventsCreateRoute: typeof DashboardEventsCreateRoute
  DashboardJobOpeningsCreateRoute: typeof DashboardJobOpeningsCreateRoute
  DashboardPostsCreateRoute: typeof DashboardPostsCreateRoute
  DashboardEventsIndexRoute: typeof DashboardEventsIndexRoute
  DashboardJobOpeningsIndexRoute: typeof DashboardJobOpeningsIndexRoute
  DashboardPostsIndexRoute: typeof DashboardPostsIndexRoute
  DashboardEventsEditIdRoute: typeof DashboardEventsEditIdRoute
  DashboardEventsShowIdRoute: typeof DashboardEventsShowIdRoute
  DashboardJobOpeningsEditIdRoute: typeof DashboardJobOpeningsEditIdRoute
  DashboardJobOpeningsShowIdRoute: typeof DashboardJobOpeningsShowIdRoute
  DashboardPostsEditIdRoute: typeof DashboardPostsEditIdRoute
  DashboardPostsShowIdRoute: typeof DashboardPostsShowIdRoute
}

const DashboardRouteRouteChildren: DashboardRouteRouteChildren = {
  DashboardUsersRouteRoute: DashboardUsersRouteRouteWithChildren,
  DashboardIndexRoute: DashboardIndexRoute,
  DashboardEventsCreateRoute: DashboardEventsCreateRoute,
  DashboardJobOpeningsCreateRoute: DashboardJobOpeningsCreateRoute,
  DashboardPostsCreateRoute: DashboardPostsCreateRoute,
  DashboardEventsIndexRoute: DashboardEventsIndexRoute,
  DashboardJobOpeningsIndexRoute: DashboardJobOpeningsIndexRoute,
  DashboardPostsIndexRoute: DashboardPostsIndexRoute,
  DashboardEventsEditIdRoute: DashboardEventsEditIdRoute,
  DashboardEventsShowIdRoute: DashboardEventsShowIdRoute,
  DashboardJobOpeningsEditIdRoute: DashboardJobOpeningsEditIdRoute,
  DashboardJobOpeningsShowIdRoute: DashboardJobOpeningsShowIdRoute,
  DashboardPostsEditIdRoute: DashboardPostsEditIdRoute,
  DashboardPostsShowIdRoute: DashboardPostsShowIdRoute,
}

const DashboardRouteRouteWithChildren = DashboardRouteRoute._addFileChildren(
  DashboardRouteRouteChildren,
)

interface AppAccountRouteRouteChildren {
  AppAccountSessionsRoute: typeof AppAccountSessionsRoute
  AppAccountSettingsRoute: typeof AppAccountSettingsRoute
  AppAccountIndexRoute: typeof AppAccountIndexRoute
}

const AppAccountRouteRouteChildren: AppAccountRouteRouteChildren = {
  AppAccountSessionsRoute: AppAccountSessionsRoute,
  AppAccountSettingsRoute: AppAccountSettingsRoute,
  AppAccountIndexRoute: AppAccountIndexRoute,
}

const AppAccountRouteRouteWithChildren = AppAccountRouteRoute._addFileChildren(
  AppAccountRouteRouteChildren,
)

interface AppCharitiesRouteRouteChildren {
  AppCharitiesIndexRoute: typeof AppCharitiesIndexRoute
  AppCharitiesProgramSlugRoute: typeof AppCharitiesProgramSlugRoute
}

const AppCharitiesRouteRouteChildren: AppCharitiesRouteRouteChildren = {
  AppCharitiesIndexRoute: AppCharitiesIndexRoute,
  AppCharitiesProgramSlugRoute: AppCharitiesProgramSlugRoute,
}

const AppCharitiesRouteRouteWithChildren =
  AppCharitiesRouteRoute._addFileChildren(AppCharitiesRouteRouteChildren)

interface AppDecreesRouteRouteChildren {
  AppDecreesUidRoute: typeof AppDecreesUidRoute
  AppDecreesIndexRoute: typeof AppDecreesIndexRoute
}

const AppDecreesRouteRouteChildren: AppDecreesRouteRouteChildren = {
  AppDecreesUidRoute: AppDecreesUidRoute,
  AppDecreesIndexRoute: AppDecreesIndexRoute,
}

const AppDecreesRouteRouteWithChildren = AppDecreesRouteRoute._addFileChildren(
  AppDecreesRouteRouteChildren,
)

interface AppRouteChildren {
  AppAccountRouteRoute: typeof AppAccountRouteRouteWithChildren
  AppCharitiesRouteRoute: typeof AppCharitiesRouteRouteWithChildren
  AppDecreesRouteRoute: typeof AppDecreesRouteRouteWithChildren
  AppAboutRoute: typeof AppAboutRoute
  AppArchbishopRoute: typeof AppArchbishopRoute
  AppCareersRoute: typeof AppCareersRoute
  AppClergyApplicationRoute: typeof AppClergyApplicationRoute
  AppContactRoute: typeof AppContactRoute
  AppDailyReadingsRoute: typeof AppDailyReadingsRoute
  AppDepartmentsRoute: typeof AppDepartmentsRoute
  AppDonateRoute: typeof AppDonateRoute
  AppEventsRoute: typeof AppEventsRoute
  AppNewsroomRoute: typeof AppNewsroomRoute
  AppParishesRoute: typeof AppParishesRoute
  AppPrivacyRoute: typeof AppPrivacyRoute
  AppRegisterParishionerRoute: typeof AppRegisterParishionerRoute
  AppServicesRoute: typeof AppServicesRoute
  AppVocationsRoute: typeof AppVocationsRoute
  AppVolunteersRoute: typeof AppVolunteersRoute
  AppIndexRoute: typeof AppIndexRoute
  AppDepartmentSlugRoute: typeof AppDepartmentSlugRoute
  AppEventSlugRoute: typeof AppEventSlugRoute
  AppPostSlugRoute: typeof AppPostSlugRoute
  AppServiceSlugRoute: typeof AppServiceSlugRoute
  AppJobSlugApplyRoute: typeof AppJobSlugApplyRoute
  AppJobSlugIndexRoute: typeof AppJobSlugIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAccountRouteRoute: AppAccountRouteRouteWithChildren,
  AppCharitiesRouteRoute: AppCharitiesRouteRouteWithChildren,
  AppDecreesRouteRoute: AppDecreesRouteRouteWithChildren,
  AppAboutRoute: AppAboutRoute,
  AppArchbishopRoute: AppArchbishopRoute,
  AppCareersRoute: AppCareersRoute,
  AppClergyApplicationRoute: AppClergyApplicationRoute,
  AppContactRoute: AppContactRoute,
  AppDailyReadingsRoute: AppDailyReadingsRoute,
  AppDepartmentsRoute: AppDepartmentsRoute,
  AppDonateRoute: AppDonateRoute,
  AppEventsRoute: AppEventsRoute,
  AppNewsroomRoute: AppNewsroomRoute,
  AppParishesRoute: AppParishesRoute,
  AppPrivacyRoute: AppPrivacyRoute,
  AppRegisterParishionerRoute: AppRegisterParishionerRoute,
  AppServicesRoute: AppServicesRoute,
  AppVocationsRoute: AppVocationsRoute,
  AppVolunteersRoute: AppVolunteersRoute,
  AppIndexRoute: AppIndexRoute,
  AppDepartmentSlugRoute: AppDepartmentSlugRoute,
  AppEventSlugRoute: AppEventSlugRoute,
  AppPostSlugRoute: AppPostSlugRoute,
  AppServiceSlugRoute: AppServiceSlugRoute,
  AppJobSlugApplyRoute: AppJobSlugApplyRoute,
  AppJobSlugIndexRoute: AppJobSlugIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  DashboardRouteRoute: DashboardRouteRouteWithChildren,
  AppRoute: AppRouteWithChildren,
  RobotsDottxtRoute: RobotsDottxtRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiPaymentFleecaCallbackRoute: ApiPaymentFleecaCallbackRoute,
  ApiPaymentFleecaWebhookRoute: ApiPaymentFleecaWebhookRoute,
  ApiPaymentStatusPaymentIdRoute: ApiPaymentStatusPaymentIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
