/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/_app'
import { Route as DashboardRouteRouteImport } from './routes/dashboard/route'
import { Route as AppIndexRouteImport } from './routes/_app/index'
import { Route as AppAboutRouteImport } from './routes/_app/about'
import { Route as AppAccountRouteRouteImport } from './routes/_app/account/route'
import { Route as AppArchbishopRouteImport } from './routes/_app/archbishop'
import { Route as AppCareersRouteImport } from './routes/_app/careers'
import { Route as AppDepartmentsRouteImport } from './routes/_app/departments'
import { Route as AppEventsRouteImport } from './routes/_app/events'
import { Route as AppNewsroomRouteImport } from './routes/_app/newsroom'
import { Route as AppParishesRouteImport } from './routes/_app/parishes'
import { Route as AppPrivacyRouteImport } from './routes/_app/privacy'
import { Route as AppRegisterParishionerRouteImport } from './routes/_app/register-parishioner'
import { Route as AppVocationsRouteImport } from './routes/_app/vocations'
import { Route as DashboardIndexRouteImport } from './routes/dashboard/index'
import { Route as DashboardUsersRouteRouteImport } from './routes/dashboard/users/route'
import { Route as AppAccountIndexRouteImport } from './routes/_app/account/index'
import { Route as AppAccountSessionsRouteImport } from './routes/_app/account/sessions'
import { Route as AppAccountSettingsRouteImport } from './routes/_app/account/settings'
import { Route as AppDepartmentSlugRouteImport } from './routes/_app/department/$slug'
import { Route as AppEventSlugRouteImport } from './routes/_app/event/$slug'
import { Route as AppPostSlugRouteImport } from './routes/_app/post/$slug'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as DashboardEventsIndexRouteImport } from './routes/dashboard/events/index'
import { Route as DashboardEventsCreateRouteImport } from './routes/dashboard/events/create'
import { Route as DashboardJobOpeningsIndexRouteImport } from './routes/dashboard/job-openings/index'
import { Route as DashboardJobOpeningsCreateRouteImport } from './routes/dashboard/job-openings/create'
import { Route as DashboardPostsIndexRouteImport } from './routes/dashboard/posts/index'
import { Route as DashboardPostsCreateRouteImport } from './routes/dashboard/posts/create'
import { Route as DashboardUsersIndexRouteImport } from './routes/dashboard/users/index'
import { Route as AppJobSlugIndexRouteImport } from './routes/_app/job/$slug.index'
import { Route as AppJobSlugApplyRouteImport } from './routes/_app/job/$slug.apply'
import { Route as DashboardEventsEditIdRouteImport } from './routes/dashboard/events/edit.$id'
import { Route as DashboardEventsShowIdRouteImport } from './routes/dashboard/events/show.$id'
import { Route as DashboardJobOpeningsEditIdRouteImport } from './routes/dashboard/job-openings/edit.$id'
import { Route as DashboardJobOpeningsShowIdRouteImport } from './routes/dashboard/job-openings/show.$id'
import { Route as DashboardPostsEditIdRouteImport } from './routes/dashboard/posts/edit.$id'
import { Route as DashboardPostsShowIdRouteImport } from './routes/dashboard/posts/show.$id'
import { Route as DashboardUsersEditIdRouteImport } from './routes/dashboard/users/edit.$id'

const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRouteRoute = DashboardRouteRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppAboutRoute = AppAboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => AppRoute,
} as any)
const AppAccountRouteRoute = AppAccountRouteRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => AppRoute,
} as any)
const AppArchbishopRoute = AppArchbishopRouteImport.update({
  id: '/archbishop',
  path: '/archbishop',
  getParentRoute: () => AppRoute,
} as any)
const AppCareersRoute = AppCareersRouteImport.update({
  id: '/careers',
  path: '/careers',
  getParentRoute: () => AppRoute,
} as any)
const AppDepartmentsRoute = AppDepartmentsRouteImport.update({
  id: '/departments',
  path: '/departments',
  getParentRoute: () => AppRoute,
} as any)
const AppEventsRoute = AppEventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => AppRoute,
} as any)
const AppNewsroomRoute = AppNewsroomRouteImport.update({
  id: '/newsroom',
  path: '/newsroom',
  getParentRoute: () => AppRoute,
} as any)
const AppParishesRoute = AppParishesRouteImport.update({
  id: '/parishes',
  path: '/parishes',
  getParentRoute: () => AppRoute,
} as any)
const AppPrivacyRoute = AppPrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => AppRoute,
} as any)
const AppRegisterParishionerRoute = AppRegisterParishionerRouteImport.update({
  id: '/register-parishioner',
  path: '/register-parishioner',
  getParentRoute: () => AppRoute,
} as any)
const AppVocationsRoute = AppVocationsRouteImport.update({
  id: '/vocations',
  path: '/vocations',
  getParentRoute: () => AppRoute,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardUsersRouteRoute = DashboardUsersRouteRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const AppAccountIndexRoute = AppAccountIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppAccountRouteRoute,
} as any)
const AppAccountSessionsRoute = AppAccountSessionsRouteImport.update({
  id: '/sessions',
  path: '/sessions',
  getParentRoute: () => AppAccountRouteRoute,
} as any)
const AppAccountSettingsRoute = AppAccountSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppAccountRouteRoute,
} as any)
const AppDepartmentSlugRoute = AppDepartmentSlugRouteImport.update({
  id: '/department/$slug',
  path: '/department/$slug',
  getParentRoute: () => AppRoute,
} as any)
const AppEventSlugRoute = AppEventSlugRouteImport.update({
  id: '/event/$slug',
  path: '/event/$slug',
  getParentRoute: () => AppRoute,
} as any)
const AppPostSlugRoute = AppPostSlugRouteImport.update({
  id: '/post/$slug',
  path: '/post/$slug',
  getParentRoute: () => AppRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardEventsIndexRoute = DashboardEventsIndexRouteImport.update({
  id: '/events/',
  path: '/events/',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardEventsCreateRoute = DashboardEventsCreateRouteImport.update({
  id: '/events/create',
  path: '/events/create',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardJobOpeningsIndexRoute =
  DashboardJobOpeningsIndexRouteImport.update({
    id: '/job-openings/',
    path: '/job-openings/',
    getParentRoute: () => DashboardRouteRoute,
  } as any)
const DashboardJobOpeningsCreateRoute =
  DashboardJobOpeningsCreateRouteImport.update({
    id: '/job-openings/create',
    path: '/job-openings/create',
    getParentRoute: () => DashboardRouteRoute,
  } as any)
const DashboardPostsIndexRoute = DashboardPostsIndexRouteImport.update({
  id: '/posts/',
  path: '/posts/',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardPostsCreateRoute = DashboardPostsCreateRouteImport.update({
  id: '/posts/create',
  path: '/posts/create',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardUsersIndexRoute = DashboardUsersIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardUsersRouteRoute,
} as any)
const AppJobSlugIndexRoute = AppJobSlugIndexRouteImport.update({
  id: '/job/$slug/',
  path: '/job/$slug/',
  getParentRoute: () => AppRoute,
} as any)
const AppJobSlugApplyRoute = AppJobSlugApplyRouteImport.update({
  id: '/job/$slug/apply',
  path: '/job/$slug/apply',
  getParentRoute: () => AppRoute,
} as any)
const DashboardEventsEditIdRoute = DashboardEventsEditIdRouteImport.update({
  id: '/events/edit/$id',
  path: '/events/edit/$id',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardEventsShowIdRoute = DashboardEventsShowIdRouteImport.update({
  id: '/events/show/$id',
  path: '/events/show/$id',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardJobOpeningsEditIdRoute =
  DashboardJobOpeningsEditIdRouteImport.update({
    id: '/job-openings/edit/$id',
    path: '/job-openings/edit/$id',
    getParentRoute: () => DashboardRouteRoute,
  } as any)
const DashboardJobOpeningsShowIdRoute =
  DashboardJobOpeningsShowIdRouteImport.update({
    id: '/job-openings/show/$id',
    path: '/job-openings/show/$id',
    getParentRoute: () => DashboardRouteRoute,
  } as any)
const DashboardPostsEditIdRoute = DashboardPostsEditIdRouteImport.update({
  id: '/posts/edit/$id',
  path: '/posts/edit/$id',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardPostsShowIdRoute = DashboardPostsShowIdRouteImport.update({
  id: '/posts/show/$id',
  path: '/posts/show/$id',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardUsersEditIdRoute = DashboardUsersEditIdRouteImport.update({
  id: '/edit/$id',
  path: '/edit/$id',
  getParentRoute: () => DashboardUsersRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/dashboard': typeof DashboardRouteRouteWithChildren
  '/': typeof AppIndexRoute
  '/account': typeof AppAccountRouteRouteWithChildren
  '/dashboard/users': typeof DashboardUsersRouteRouteWithChildren
  '/about': typeof AppAboutRoute
  '/archbishop': typeof AppArchbishopRoute
  '/careers': typeof AppCareersRoute
  '/departments': typeof AppDepartmentsRoute
  '/events': typeof AppEventsRoute
  '/newsroom': typeof AppNewsroomRoute
  '/parishes': typeof AppParishesRoute
  '/privacy': typeof AppPrivacyRoute
  '/register-parishioner': typeof AppRegisterParishionerRoute
  '/vocations': typeof AppVocationsRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/account/sessions': typeof AppAccountSessionsRoute
  '/account/settings': typeof AppAccountSettingsRoute
  '/department/$slug': typeof AppDepartmentSlugRoute
  '/event/$slug': typeof AppEventSlugRoute
  '/post/$slug': typeof AppPostSlugRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/dashboard/events/create': typeof DashboardEventsCreateRoute
  '/dashboard/job-openings/create': typeof DashboardJobOpeningsCreateRoute
  '/dashboard/posts/create': typeof DashboardPostsCreateRoute
  '/account/': typeof AppAccountIndexRoute
  '/dashboard/events/': typeof DashboardEventsIndexRoute
  '/dashboard/job-openings/': typeof DashboardJobOpeningsIndexRoute
  '/dashboard/posts/': typeof DashboardPostsIndexRoute
  '/dashboard/users/': typeof DashboardUsersIndexRoute
  '/job/$slug/apply': typeof AppJobSlugApplyRoute
  '/dashboard/events/edit/$id': typeof DashboardEventsEditIdRoute
  '/dashboard/events/show/$id': typeof DashboardEventsShowIdRoute
  '/dashboard/job-openings/edit/$id': typeof DashboardJobOpeningsEditIdRoute
  '/dashboard/job-openings/show/$id': typeof DashboardJobOpeningsShowIdRoute
  '/dashboard/posts/edit/$id': typeof DashboardPostsEditIdRoute
  '/dashboard/posts/show/$id': typeof DashboardPostsShowIdRoute
  '/dashboard/users/edit/$id': typeof DashboardUsersEditIdRoute
  '/job/$slug/': typeof AppJobSlugIndexRoute
}
export interface FileRoutesByTo {
  '/about': typeof AppAboutRoute
  '/archbishop': typeof AppArchbishopRoute
  '/careers': typeof AppCareersRoute
  '/departments': typeof AppDepartmentsRoute
  '/events': typeof AppEventsRoute
  '/newsroom': typeof AppNewsroomRoute
  '/parishes': typeof AppParishesRoute
  '/privacy': typeof AppPrivacyRoute
  '/register-parishioner': typeof AppRegisterParishionerRoute
  '/vocations': typeof AppVocationsRoute
  '/': typeof AppIndexRoute
  '/dashboard': typeof DashboardIndexRoute
  '/account/sessions': typeof AppAccountSessionsRoute
  '/account/settings': typeof AppAccountSettingsRoute
  '/department/$slug': typeof AppDepartmentSlugRoute
  '/event/$slug': typeof AppEventSlugRoute
  '/post/$slug': typeof AppPostSlugRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/dashboard/events/create': typeof DashboardEventsCreateRoute
  '/dashboard/job-openings/create': typeof DashboardJobOpeningsCreateRoute
  '/dashboard/posts/create': typeof DashboardPostsCreateRoute
  '/account': typeof AppAccountIndexRoute
  '/dashboard/events': typeof DashboardEventsIndexRoute
  '/dashboard/job-openings': typeof DashboardJobOpeningsIndexRoute
  '/dashboard/posts': typeof DashboardPostsIndexRoute
  '/dashboard/users': typeof DashboardUsersIndexRoute
  '/job/$slug/apply': typeof AppJobSlugApplyRoute
  '/dashboard/events/edit/$id': typeof DashboardEventsEditIdRoute
  '/dashboard/events/show/$id': typeof DashboardEventsShowIdRoute
  '/dashboard/job-openings/edit/$id': typeof DashboardJobOpeningsEditIdRoute
  '/dashboard/job-openings/show/$id': typeof DashboardJobOpeningsShowIdRoute
  '/dashboard/posts/edit/$id': typeof DashboardPostsEditIdRoute
  '/dashboard/posts/show/$id': typeof DashboardPostsShowIdRoute
  '/dashboard/users/edit/$id': typeof DashboardUsersEditIdRoute
  '/job/$slug': typeof AppJobSlugIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/dashboard': typeof DashboardRouteRouteWithChildren
  '/_app': typeof AppRouteWithChildren
  '/_app/account': typeof AppAccountRouteRouteWithChildren
  '/dashboard/users': typeof DashboardUsersRouteRouteWithChildren
  '/_app/about': typeof AppAboutRoute
  '/_app/archbishop': typeof AppArchbishopRoute
  '/_app/careers': typeof AppCareersRoute
  '/_app/departments': typeof AppDepartmentsRoute
  '/_app/events': typeof AppEventsRoute
  '/_app/newsroom': typeof AppNewsroomRoute
  '/_app/parishes': typeof AppParishesRoute
  '/_app/privacy': typeof AppPrivacyRoute
  '/_app/register-parishioner': typeof AppRegisterParishionerRoute
  '/_app/vocations': typeof AppVocationsRoute
  '/_app/': typeof AppIndexRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/_app/account/sessions': typeof AppAccountSessionsRoute
  '/_app/account/settings': typeof AppAccountSettingsRoute
  '/_app/department/$slug': typeof AppDepartmentSlugRoute
  '/_app/event/$slug': typeof AppEventSlugRoute
  '/_app/post/$slug': typeof AppPostSlugRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/dashboard/events/create': typeof DashboardEventsCreateRoute
  '/dashboard/job-openings/create': typeof DashboardJobOpeningsCreateRoute
  '/dashboard/posts/create': typeof DashboardPostsCreateRoute
  '/_app/account/': typeof AppAccountIndexRoute
  '/dashboard/events/': typeof DashboardEventsIndexRoute
  '/dashboard/job-openings/': typeof DashboardJobOpeningsIndexRoute
  '/dashboard/posts/': typeof DashboardPostsIndexRoute
  '/dashboard/users/': typeof DashboardUsersIndexRoute
  '/_app/job/$slug/apply': typeof AppJobSlugApplyRoute
  '/dashboard/events/edit/$id': typeof DashboardEventsEditIdRoute
  '/dashboard/events/show/$id': typeof DashboardEventsShowIdRoute
  '/dashboard/job-openings/edit/$id': typeof DashboardJobOpeningsEditIdRoute
  '/dashboard/job-openings/show/$id': typeof DashboardJobOpeningsShowIdRoute
  '/dashboard/posts/edit/$id': typeof DashboardPostsEditIdRoute
  '/dashboard/posts/show/$id': typeof DashboardPostsShowIdRoute
  '/dashboard/users/edit/$id': typeof DashboardUsersEditIdRoute
  '/_app/job/$slug/': typeof AppJobSlugIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/dashboard'
    | '/'
    | '/account'
    | '/dashboard/users'
    | '/about'
    | '/archbishop'
    | '/careers'
    | '/departments'
    | '/events'
    | '/newsroom'
    | '/parishes'
    | '/privacy'
    | '/register-parishioner'
    | '/vocations'
    | '/dashboard/'
    | '/account/sessions'
    | '/account/settings'
    | '/department/$slug'
    | '/event/$slug'
    | '/post/$slug'
    | '/api/auth/$'
    | '/dashboard/events/create'
    | '/dashboard/job-openings/create'
    | '/dashboard/posts/create'
    | '/account/'
    | '/dashboard/events/'
    | '/dashboard/job-openings/'
    | '/dashboard/posts/'
    | '/dashboard/users/'
    | '/job/$slug/apply'
    | '/dashboard/events/edit/$id'
    | '/dashboard/events/show/$id'
    | '/dashboard/job-openings/edit/$id'
    | '/dashboard/job-openings/show/$id'
    | '/dashboard/posts/edit/$id'
    | '/dashboard/posts/show/$id'
    | '/dashboard/users/edit/$id'
    | '/job/$slug/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/about'
    | '/archbishop'
    | '/careers'
    | '/departments'
    | '/events'
    | '/newsroom'
    | '/parishes'
    | '/privacy'
    | '/register-parishioner'
    | '/vocations'
    | '/'
    | '/dashboard'
    | '/account/sessions'
    | '/account/settings'
    | '/department/$slug'
    | '/event/$slug'
    | '/post/$slug'
    | '/api/auth/$'
    | '/dashboard/events/create'
    | '/dashboard/job-openings/create'
    | '/dashboard/posts/create'
    | '/account'
    | '/dashboard/events'
    | '/dashboard/job-openings'
    | '/dashboard/posts'
    | '/dashboard/users'
    | '/job/$slug/apply'
    | '/dashboard/events/edit/$id'
    | '/dashboard/events/show/$id'
    | '/dashboard/job-openings/edit/$id'
    | '/dashboard/job-openings/show/$id'
    | '/dashboard/posts/edit/$id'
    | '/dashboard/posts/show/$id'
    | '/dashboard/users/edit/$id'
    | '/job/$slug'
  id:
    | '__root__'
    | '/dashboard'
    | '/_app'
    | '/_app/account'
    | '/dashboard/users'
    | '/_app/about'
    | '/_app/archbishop'
    | '/_app/careers'
    | '/_app/departments'
    | '/_app/events'
    | '/_app/newsroom'
    | '/_app/parishes'
    | '/_app/privacy'
    | '/_app/register-parishioner'
    | '/_app/vocations'
    | '/_app/'
    | '/dashboard/'
    | '/_app/account/sessions'
    | '/_app/account/settings'
    | '/_app/department/$slug'
    | '/_app/event/$slug'
    | '/_app/post/$slug'
    | '/api/auth/$'
    | '/dashboard/events/create'
    | '/dashboard/job-openings/create'
    | '/dashboard/posts/create'
    | '/_app/account/'
    | '/dashboard/events/'
    | '/dashboard/job-openings/'
    | '/dashboard/posts/'
    | '/dashboard/users/'
    | '/_app/job/$slug/apply'
    | '/dashboard/events/edit/$id'
    | '/dashboard/events/show/$id'
    | '/dashboard/job-openings/edit/$id'
    | '/dashboard/job-openings/show/$id'
    | '/dashboard/posts/edit/$id'
    | '/dashboard/posts/show/$id'
    | '/dashboard/users/edit/$id'
    | '/_app/job/$slug/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  DashboardRouteRoute: typeof DashboardRouteRouteWithChildren
  AppRoute: typeof AppRouteWithChildren
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/about': {
      id: '/_app/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AppAboutRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/account': {
      id: '/_app/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AppAccountRouteRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/archbishop': {
      id: '/_app/archbishop'
      path: '/archbishop'
      fullPath: '/archbishop'
      preLoaderRoute: typeof AppArchbishopRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/careers': {
      id: '/_app/careers'
      path: '/careers'
      fullPath: '/careers'
      preLoaderRoute: typeof AppCareersRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/departments': {
      id: '/_app/departments'
      path: '/departments'
      fullPath: '/departments'
      preLoaderRoute: typeof AppDepartmentsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/events': {
      id: '/_app/events'
      path: '/events'
      fullPath: '/events'
      preLoaderRoute: typeof AppEventsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/newsroom': {
      id: '/_app/newsroom'
      path: '/newsroom'
      fullPath: '/newsroom'
      preLoaderRoute: typeof AppNewsroomRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/parishes': {
      id: '/_app/parishes'
      path: '/parishes'
      fullPath: '/parishes'
      preLoaderRoute: typeof AppParishesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/privacy': {
      id: '/_app/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof AppPrivacyRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/register-parishioner': {
      id: '/_app/register-parishioner'
      path: '/register-parishioner'
      fullPath: '/register-parishioner'
      preLoaderRoute: typeof AppRegisterParishionerRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/vocations': {
      id: '/_app/vocations'
      path: '/vocations'
      fullPath: '/vocations'
      preLoaderRoute: typeof AppVocationsRouteImport
      parentRoute: typeof AppRoute
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/users': {
      id: '/dashboard/users'
      path: '/users'
      fullPath: '/dashboard/users'
      preLoaderRoute: typeof DashboardUsersRouteRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/_app/account/': {
      id: '/_app/account/'
      path: '/'
      fullPath: '/account/'
      preLoaderRoute: typeof AppAccountIndexRouteImport
      parentRoute: typeof AppAccountRouteRoute
    }
    '/_app/account/sessions': {
      id: '/_app/account/sessions'
      path: '/sessions'
      fullPath: '/account/sessions'
      preLoaderRoute: typeof AppAccountSessionsRouteImport
      parentRoute: typeof AppAccountRouteRoute
    }
    '/_app/account/settings': {
      id: '/_app/account/settings'
      path: '/settings'
      fullPath: '/account/settings'
      preLoaderRoute: typeof AppAccountSettingsRouteImport
      parentRoute: typeof AppAccountRouteRoute
    }
    '/_app/department/$slug': {
      id: '/_app/department/$slug'
      path: '/department/$slug'
      fullPath: '/department/$slug'
      preLoaderRoute: typeof AppDepartmentSlugRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/event/$slug': {
      id: '/_app/event/$slug'
      path: '/event/$slug'
      fullPath: '/event/$slug'
      preLoaderRoute: typeof AppEventSlugRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/post/$slug': {
      id: '/_app/post/$slug'
      path: '/post/$slug'
      fullPath: '/post/$slug'
      preLoaderRoute: typeof AppPostSlugRouteImport
      parentRoute: typeof AppRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/events/': {
      id: '/dashboard/events/'
      path: '/events'
      fullPath: '/dashboard/events/'
      preLoaderRoute: typeof DashboardEventsIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/events/create': {
      id: '/dashboard/events/create'
      path: '/events/create'
      fullPath: '/dashboard/events/create'
      preLoaderRoute: typeof DashboardEventsCreateRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/job-openings/': {
      id: '/dashboard/job-openings/'
      path: '/job-openings'
      fullPath: '/dashboard/job-openings/'
      preLoaderRoute: typeof DashboardJobOpeningsIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/job-openings/create': {
      id: '/dashboard/job-openings/create'
      path: '/job-openings/create'
      fullPath: '/dashboard/job-openings/create'
      preLoaderRoute: typeof DashboardJobOpeningsCreateRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/posts/': {
      id: '/dashboard/posts/'
      path: '/posts'
      fullPath: '/dashboard/posts/'
      preLoaderRoute: typeof DashboardPostsIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/posts/create': {
      id: '/dashboard/posts/create'
      path: '/posts/create'
      fullPath: '/dashboard/posts/create'
      preLoaderRoute: typeof DashboardPostsCreateRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/users/': {
      id: '/dashboard/users/'
      path: '/'
      fullPath: '/dashboard/users/'
      preLoaderRoute: typeof DashboardUsersIndexRouteImport
      parentRoute: typeof DashboardUsersRouteRoute
    }
    '/_app/job/$slug/': {
      id: '/_app/job/$slug/'
      path: '/job/$slug'
      fullPath: '/job/$slug/'
      preLoaderRoute: typeof AppJobSlugIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/job/$slug/apply': {
      id: '/_app/job/$slug/apply'
      path: '/job/$slug/apply'
      fullPath: '/job/$slug/apply'
      preLoaderRoute: typeof AppJobSlugApplyRouteImport
      parentRoute: typeof AppRoute
    }
    '/dashboard/events/edit/$id': {
      id: '/dashboard/events/edit/$id'
      path: '/events/edit/$id'
      fullPath: '/dashboard/events/edit/$id'
      preLoaderRoute: typeof DashboardEventsEditIdRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/events/show/$id': {
      id: '/dashboard/events/show/$id'
      path: '/events/show/$id'
      fullPath: '/dashboard/events/show/$id'
      preLoaderRoute: typeof DashboardEventsShowIdRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/job-openings/edit/$id': {
      id: '/dashboard/job-openings/edit/$id'
      path: '/job-openings/edit/$id'
      fullPath: '/dashboard/job-openings/edit/$id'
      preLoaderRoute: typeof DashboardJobOpeningsEditIdRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/job-openings/show/$id': {
      id: '/dashboard/job-openings/show/$id'
      path: '/job-openings/show/$id'
      fullPath: '/dashboard/job-openings/show/$id'
      preLoaderRoute: typeof DashboardJobOpeningsShowIdRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/posts/edit/$id': {
      id: '/dashboard/posts/edit/$id'
      path: '/posts/edit/$id'
      fullPath: '/dashboard/posts/edit/$id'
      preLoaderRoute: typeof DashboardPostsEditIdRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/posts/show/$id': {
      id: '/dashboard/posts/show/$id'
      path: '/posts/show/$id'
      fullPath: '/dashboard/posts/show/$id'
      preLoaderRoute: typeof DashboardPostsShowIdRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/users/edit/$id': {
      id: '/dashboard/users/edit/$id'
      path: '/edit/$id'
      fullPath: '/dashboard/users/edit/$id'
      preLoaderRoute: typeof DashboardUsersEditIdRouteImport
      parentRoute: typeof DashboardUsersRouteRoute
    }
  }
}

interface DashboardUsersRouteRouteChildren {
  DashboardUsersIndexRoute: typeof DashboardUsersIndexRoute
  DashboardUsersEditIdRoute: typeof DashboardUsersEditIdRoute
}

const DashboardUsersRouteRouteChildren: DashboardUsersRouteRouteChildren = {
  DashboardUsersIndexRoute: DashboardUsersIndexRoute,
  DashboardUsersEditIdRoute: DashboardUsersEditIdRoute,
}

const DashboardUsersRouteRouteWithChildren =
  DashboardUsersRouteRoute._addFileChildren(DashboardUsersRouteRouteChildren)

interface DashboardRouteRouteChildren {
  DashboardUsersRouteRoute: typeof DashboardUsersRouteRouteWithChildren
  DashboardIndexRoute: typeof DashboardIndexRoute
  DashboardEventsCreateRoute: typeof DashboardEventsCreateRoute
  DashboardJobOpeningsCreateRoute: typeof DashboardJobOpeningsCreateRoute
  DashboardPostsCreateRoute: typeof DashboardPostsCreateRoute
  DashboardEventsIndexRoute: typeof DashboardEventsIndexRoute
  DashboardJobOpeningsIndexRoute: typeof DashboardJobOpeningsIndexRoute
  DashboardPostsIndexRoute: typeof DashboardPostsIndexRoute
  DashboardEventsEditIdRoute: typeof DashboardEventsEditIdRoute
  DashboardEventsShowIdRoute: typeof DashboardEventsShowIdRoute
  DashboardJobOpeningsEditIdRoute: typeof DashboardJobOpeningsEditIdRoute
  DashboardJobOpeningsShowIdRoute: typeof DashboardJobOpeningsShowIdRoute
  DashboardPostsEditIdRoute: typeof DashboardPostsEditIdRoute
  DashboardPostsShowIdRoute: typeof DashboardPostsShowIdRoute
}

const DashboardRouteRouteChildren: DashboardRouteRouteChildren = {
  DashboardUsersRouteRoute: DashboardUsersRouteRouteWithChildren,
  DashboardIndexRoute: DashboardIndexRoute,
  DashboardEventsCreateRoute: DashboardEventsCreateRoute,
  DashboardJobOpeningsCreateRoute: DashboardJobOpeningsCreateRoute,
  DashboardPostsCreateRoute: DashboardPostsCreateRoute,
  DashboardEventsIndexRoute: DashboardEventsIndexRoute,
  DashboardJobOpeningsIndexRoute: DashboardJobOpeningsIndexRoute,
  DashboardPostsIndexRoute: DashboardPostsIndexRoute,
  DashboardEventsEditIdRoute: DashboardEventsEditIdRoute,
  DashboardEventsShowIdRoute: DashboardEventsShowIdRoute,
  DashboardJobOpeningsEditIdRoute: DashboardJobOpeningsEditIdRoute,
  DashboardJobOpeningsShowIdRoute: DashboardJobOpeningsShowIdRoute,
  DashboardPostsEditIdRoute: DashboardPostsEditIdRoute,
  DashboardPostsShowIdRoute: DashboardPostsShowIdRoute,
}

const DashboardRouteRouteWithChildren = DashboardRouteRoute._addFileChildren(
  DashboardRouteRouteChildren,
)

interface AppAccountRouteRouteChildren {
  AppAccountSessionsRoute: typeof AppAccountSessionsRoute
  AppAccountSettingsRoute: typeof AppAccountSettingsRoute
  AppAccountIndexRoute: typeof AppAccountIndexRoute
}

const AppAccountRouteRouteChildren: AppAccountRouteRouteChildren = {
  AppAccountSessionsRoute: AppAccountSessionsRoute,
  AppAccountSettingsRoute: AppAccountSettingsRoute,
  AppAccountIndexRoute: AppAccountIndexRoute,
}

const AppAccountRouteRouteWithChildren = AppAccountRouteRoute._addFileChildren(
  AppAccountRouteRouteChildren,
)

interface AppRouteChildren {
  AppAccountRouteRoute: typeof AppAccountRouteRouteWithChildren
  AppAboutRoute: typeof AppAboutRoute
  AppArchbishopRoute: typeof AppArchbishopRoute
  AppCareersRoute: typeof AppCareersRoute
  AppDepartmentsRoute: typeof AppDepartmentsRoute
  AppEventsRoute: typeof AppEventsRoute
  AppNewsroomRoute: typeof AppNewsroomRoute
  AppParishesRoute: typeof AppParishesRoute
  AppPrivacyRoute: typeof AppPrivacyRoute
  AppRegisterParishionerRoute: typeof AppRegisterParishionerRoute
  AppVocationsRoute: typeof AppVocationsRoute
  AppIndexRoute: typeof AppIndexRoute
  AppDepartmentSlugRoute: typeof AppDepartmentSlugRoute
  AppEventSlugRoute: typeof AppEventSlugRoute
  AppPostSlugRoute: typeof AppPostSlugRoute
  AppJobSlugApplyRoute: typeof AppJobSlugApplyRoute
  AppJobSlugIndexRoute: typeof AppJobSlugIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAccountRouteRoute: AppAccountRouteRouteWithChildren,
  AppAboutRoute: AppAboutRoute,
  AppArchbishopRoute: AppArchbishopRoute,
  AppCareersRoute: AppCareersRoute,
  AppDepartmentsRoute: AppDepartmentsRoute,
  AppEventsRoute: AppEventsRoute,
  AppNewsroomRoute: AppNewsroomRoute,
  AppParishesRoute: AppParishesRoute,
  AppPrivacyRoute: AppPrivacyRoute,
  AppRegisterParishionerRoute: AppRegisterParishionerRoute,
  AppVocationsRoute: AppVocationsRoute,
  AppIndexRoute: AppIndexRoute,
  AppDepartmentSlugRoute: AppDepartmentSlugRoute,
  AppEventSlugRoute: AppEventSlugRoute,
  AppPostSlugRoute: AppPostSlugRoute,
  AppJobSlugApplyRoute: AppJobSlugApplyRoute,
  AppJobSlugIndexRoute: AppJobSlugIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  DashboardRouteRoute: DashboardRouteRouteWithChildren,
  AppRoute: AppRouteWithChildren,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
