name: Deploy to Render

on:
    workflow_dispatch:

jobs:
    deploy:
        runs-on: ubuntu-latest
        if: github.ref == 'refs/heads/prod'

        steps:
            - name: Check out repository
              uses: actions/checkout@v4
              with:
                  fetch-depth: 1


            - name: Decode .env file
              run: |
                echo "$ENV_FILE" | base64 --decode > .env
              env:
                ENV_FILE: ${{ secrets.ENV_FILE }}

            - name: Convert .env to JSON
              run: |
                jq -nR 'reduce inputs as $i ({}; . + ( ($i|split("=")) as $pair | {($pair[0]): $pair[1]} ))' < .env > env.json

            - name: Update Render environment variables
              if: steps.env-setup.outputs.env_vars != '[]'
              run: |
                  curl -X PUT "https://api.render.com/v1/services/$RENDER_SERVICE_ID/env-vars" \
                    -H "Authorization: Bearer $RENDER_API_KEY" \
                    -H "Content-Type: application/json" \
                    -d @env.json
              env:
                  RENDER_API_KEY: ${{ secrets.RENDER_API_KEY }}
                  RENDER_SERVICE_ID: ${{ secrets.RENDER_SERVICE_ID }}

            - name: Trigger Render deployment
              id: deploy
              run: |
                  response=$(curl -s -w "\n%{http_code}" "${{ secrets.RENDER_DEPLOY_HOOK_URL }}")

                  status_code=$(echo "$response" | tail -n1)
                  response_body=$(echo "$response" | sed '$d')

                  if [ "$status_code" -ne 200 ]; then
                    echo "Deployment trigger failed. Status: $status_code"
                    echo "Response: $response_body"
                    exit 1
                  fi

                  echo "Deployment triggered successfully"
